using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BusinessEntities.ConsentForms
{
    public class OccupationalTherapyForm
    {
        public int potId { get; set; }
        public int pot_appId { get; set; }
        public string pot_1 { get; set; }
        public string pot_2 { get; set; }
        public string pot_3 { get; set; }
        public string pot_4 { get; set; }
        public string pot_5 { get; set; }
        public string pot_6 { get; set; }
        public string pot_7 { get; set; }
        public string pot_8 { get; set; }
        public string pot_9 { get; set; }
        public string pot_10 { get; set; }
        public string pot_11 { get; set; }
        public string pot_12 { get; set; }
        public string pot_13 { get; set; }
        public string pot_14 { get; set; }
        public string pot_15 { get; set; }
        public string pot_16 { get; set; }
        public string pot_17 { get; set; }
        public string pot_18 { get; set; }
        public string pot_19 { get; set; }
        //public string pot_20 { get; set; }
        //public string pot_21 { get; set; }
        public string pot_22 { get; set; }
        public string pot_23 { get; set; }
        public string pot_24 { get; set; }
        public string pot_25 { get; set; }
        public string pot_26 { get; set; }
        public string pot_27 { get; set; }
        public string pot_28 { get; set; }
        public string pot_29 { get; set; }
        public string pot_30{ get; set; }
        public string pot_31 { get; set; }
        public string pot_32 { get; set; }
        public string pot_33 { get; set; }
        public string pot_34 { get; set; }
        public string pot_35 { get; set; }
        public string pot_36 { get; set; }
        public string pot_37 { get; set; }
        public string pot_38 { get; set; }
        public string pot_39 { get; set; }
        public string pot_40 { get; set; }
        public string pot_41 { get; set; }
        public string pot_42 { get; set; }
        public string pot_43 { get; set; }
        public string pot_44 { get; set; }
        public string pot_45 { get; set; }
        public string pot_46 { get; set; }
        public string pot_47 { get; set; }
        public string pot_48 { get; set; }
        public string pot_49 { get; set; }
        public string pot_50 { get; set; }
        public string pot_51 { get; set; }
        public string pot_52 { get; set; }
        public string pot_53 { get; set; }
        public string pot_54 { get; set; }
        public string pot_55 { get; set; }
        public string pot_56 { get; set; }
        public string pot_57 { get; set; }
        public string pot_58 { get; set; }
        public string pot_59 { get; set; }
        public string pot_60 { get; set; }
        public string pot_61 { get; set; }
        public string pot_62 { get; set; }
        public string pot_63 { get; set; }
        public string pot_64 { get; set; }
        public string pot_65 { get; set; }
        public string pot_66 { get; set; }
        public string pot_67 { get; set; }
        public string pot_68 { get; set; }
        public string pot_69 { get; set; }
        public string pot_70 { get; set; }
        public string pot_71 { get; set; }
        public string pot_72 { get; set; }
        public string pot_73 { get; set; }
        public string pot_74 { get; set; }
        public string pot_75 { get; set; }
        public string pot_76 { get; set; }
        public string pot_77 { get; set; }
        public string pot_78 { get; set; }
        public string pot_79 { get; set; }
        public string pot_80 { get; set; }
        public string pot_81 { get; set; }
        public string pot_82 { get; set; }
        public string pot_83 { get; set; }
        public string pot_84 { get; set; }
        public string pot_85 { get; set; }
        public string pot_86 { get; set; }
        public string pot_87 { get; set; }
        public string pot_88 { get; set; }
        public string pot_89 { get; set; }
        public string pot_90 { get; set; }
        public string pot_91 { get; set; }
        public string pot_92 { get; set; }
        public string pot_93 { get; set; }
        public string pot_94 { get; set; }
        public string pot_95 { get; set; }
        public string pot_96 { get; set; }
        public string pot_97 { get; set; }
        public string pot_98 { get; set; }
        public string pot_99 { get; set; }
        public string pot_100 { get; set; }
        public string pot_101 { get; set; }
        public string pot_102 { get; set; }
        public string pot_103 { get; set; }
        public string pot_104 { get; set; }
        public string pot_105 { get; set; }
        public string pot_106 { get; set; }
        public string pot_107 { get; set; }
        public string pot_108 { get; set; }
        public string pot_109 { get; set; }
        public string pot_110 { get; set; }
        public string pot_111 { get; set; }
        public string pot_112 { get; set; }
        public string pot_113 { get; set; }
        public string pot_114 { get; set; }
        public string pot_115 { get; set; }
        public string pot_116 { get; set; }
        public string pot_117 { get; set; }
        public string pot_118 { get; set; }
        public string pot_119 { get; set; }
        public string pot_120 { get; set; }
        public string pot_121 { get; set; }
        public string pot_122 { get; set; }
        public string pot_123 { get; set; }
        public string pot_124 { get; set; }
        public string pot_125 { get; set; }
        public string pot_126 { get; set; }
        public string pot_127 { get; set; }
        public string pot_128 { get; set; }
        public string pot_129 { get; set; }
        public string pot_130 { get; set; }
        public string pot_131 { get; set; }
        public string pot_132 { get; set; }
        public string pot_133 { get; set; }
        public string pot_134 { get; set; }
        public string pot_135 { get; set; }
        public string pot_136 { get; set; }
        public string pot_137 { get; set; }
        public string pot_138 { get; set; }
        public string pot_139 { get; set; }
        public string pot_140 { get; set; }
        public string pot_141 { get; set; }
        public string pot_142 { get; set; }
        public string pot_143 { get; set; }
        public string pot_144 { get; set; }
        public string pot_145 { get; set; }
        public string pot_146 { get; set; }
        public string pot_147 { get; set; }
        public string pot_148 { get; set; }
        public string pot_149 { get; set; }
        public string pot_radio1 { get; set; }
        public string pot_radio2 { get; set; }
        public string pot_date1 { get; set; }
        public string pot_time1 { get; set; }
        public string pot_status { get; set; }
        public DateTime pot_date_modified { get; set; }

    }

}
