//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AAFIYA_CLAIM
    {
        public int ccaId { get; set; }
        public Nullable<int> cca_appId { get; set; }
        public string cca_1 { get; set; }
        public string cca_2 { get; set; }
        public string cca_3 { get; set; }
        public string cca_4 { get; set; }
        public string cca_5 { get; set; }
        public string cca_6 { get; set; }
        public string cca_7 { get; set; }
        public string cca_8 { get; set; }
        public string cca_9 { get; set; }
        public string cca_10 { get; set; }
        public string cca_11 { get; set; }
        public string cca_12 { get; set; }
        public string cca_13 { get; set; }
        public string cca_14 { get; set; }
        public string cca_15 { get; set; }
        public string cca_16 { get; set; }
        public string cca_17 { get; set; }
        public string cca_18 { get; set; }
        public string cca_19 { get; set; }
        public string cca_20 { get; set; }
        public string cca_chk { get; set; }
        public Nullable<System.DateTime> cca_date1 { get; set; }
        public Nullable<System.DateTime> cca_date2 { get; set; }
        public string cca_status { get; set; }
        public Nullable<int> cca_madeby { get; set; }
        public Nullable<int> cca_modifyby { get; set; }
        public Nullable<System.DateTime> cca_date_created { get; set; }
        public Nullable<System.DateTime> cca_date_modified { get; set; }
    }
}
