//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Adult_Assessment_Consent
    {
        public int aacId { get; set; }
        public Nullable<int> aac_appId { get; set; }
        public string aac_1 { get; set; }
        public string aac_status { get; set; }
        public Nullable<int> aac_made_by { get; set; }
        public Nullable<System.DateTime> aac_date_created { get; set; }
        public Nullable<int> aac_modified_by { get; set; }
        public Nullable<System.DateTime> aac_date_modified { get; set; }
    }
}
