//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Aetna_Reimbursement
    {
        public int car_Id { get; set; }
        public Nullable<int> car_appId { get; set; }
        public string car_checkbox { get; set; }
        public string car_r1 { get; set; }
        public string car_r2 { get; set; }
        public string car_r3 { get; set; }
        public string car_r4 { get; set; }
        public string car_r5 { get; set; }
        public string car_r6 { get; set; }
        public string car_r7 { get; set; }
        public string car_r8 { get; set; }
        public string car_r9 { get; set; }
        public string car_r10 { get; set; }
        public string car_r11 { get; set; }
        public string car_r12 { get; set; }
        public string car_r13 { get; set; }
        public string car_r14 { get; set; }
        public string car_r15 { get; set; }
        public string car_r16 { get; set; }
        public string car_r17 { get; set; }
        public string car_r18 { get; set; }
        public string car_r19 { get; set; }
        public string car_r20 { get; set; }
        public string car_r21 { get; set; }
        public string car_r22 { get; set; }
        public string car_r23 { get; set; }
        public string car_r24 { get; set; }
        public string car_r25 { get; set; }
        public string car_r26 { get; set; }
        public string car_r27 { get; set; }
        public string car_r28 { get; set; }
        public string car_r29 { get; set; }
        public string car_r30 { get; set; }
        public string car_r31 { get; set; }
        public string car_r32 { get; set; }
        public string car_r33 { get; set; }
        public string car_r34 { get; set; }
        public string car_r35 { get; set; }
        public string car_r36 { get; set; }
        public string car_r37 { get; set; }
        public string car_r38 { get; set; }
        public string car_r39 { get; set; }
        public string car_r40 { get; set; }
        public string car_r41 { get; set; }
        public string car_r42 { get; set; }
        public string car_r43 { get; set; }
        public string car_r44 { get; set; }
        public string car_r45 { get; set; }
        public string car_r46 { get; set; }
        public string car_r47 { get; set; }
        public string car_r48 { get; set; }
        public string car_r49 { get; set; }
        public string car_r50 { get; set; }
        public string car_r51 { get; set; }
        public string car_r52 { get; set; }
        public string car_r53 { get; set; }
        public string car_r54 { get; set; }
        public string car_r55 { get; set; }
        public string car_r56 { get; set; }
        public string car_r57 { get; set; }
        public string car_r58 { get; set; }
        public string car_r59 { get; set; }
        public string car_r60 { get; set; }
        public string car_r61 { get; set; }
        public string car_r62 { get; set; }
        public string car_r63 { get; set; }
        public string car_r64 { get; set; }
        public string car_r65 { get; set; }
        public string car_r66 { get; set; }
        public string car_r67 { get; set; }
        public string car_r68 { get; set; }
        public string car_r69 { get; set; }
        public string car_r70 { get; set; }
        public string car_r71 { get; set; }
        public string car_r72 { get; set; }
        public string car_r73 { get; set; }
        public string car_r74 { get; set; }
        public string car_r75 { get; set; }
        public Nullable<System.DateTime> car_d1 { get; set; }
        public Nullable<System.DateTime> car_d2 { get; set; }
        public Nullable<System.DateTime> car_d3 { get; set; }
        public Nullable<System.DateTime> car_d4 { get; set; }
        public Nullable<System.DateTime> car_d5 { get; set; }
        public Nullable<System.DateTime> car_d6 { get; set; }
        public Nullable<System.DateTime> car_d7 { get; set; }
        public Nullable<System.DateTime> car_d8 { get; set; }
        public Nullable<System.DateTime> car_date_created { get; set; }
        public Nullable<System.DateTime> car_date_modified { get; set; }
        public string car_status { get; set; }
        public Nullable<int> car_madeby { get; set; }
        public Nullable<int> car_modifyby { get; set; }
    }
}
