//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_After_Operation_Form
    {
        public int aofId { get; set; }
        public Nullable<int> aof_appId { get; set; }
        public string aof_status { get; set; }
        public Nullable<int> aof_made_by { get; set; }
        public Nullable<System.DateTime> aof_date_created { get; set; }
        public Nullable<int> aof_modified_by { get; set; }
        public Nullable<System.DateTime> aof_date_modified { get; set; }
    }
}
