//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ALICO
    {
        public int aliId { get; set; }
        public Nullable<int> ali_appId { get; set; }
        public string ali_method { get; set; }
        public string ali_ins1 { get; set; }
        public string ali_ins2 { get; set; }
        public string ali_ins3 { get; set; }
        public string ali_ins4 { get; set; }
        public string ali_ins5 { get; set; }
        public string ali_ins6 { get; set; }
        public string ali_ins7 { get; set; }
        public string ali_ins8 { get; set; }
        public string ali_ins9 { get; set; }
        public string ali_ins10 { get; set; }
        public string ali_ins11 { get; set; }
        public string ali_ins12 { get; set; }
        public string ali_ins13 { get; set; }
        public string ali_ins14 { get; set; }
        public string ali_ins15 { get; set; }
        public string ali_checkbox { get; set; }
        public string ali_ins16 { get; set; }
        public Nullable<System.DateTime> ali_date_created { get; set; }
        public Nullable<System.DateTime> ali_date_modified { get; set; }
    }
}
