//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ALLERGIES
    {
        public int allId { get; set; }
        public Nullable<int> all_appId { get; set; }
        public string allergies { get; set; }
        public string all_for { get; set; }
        public string all_pexam { get; set; }
        public string all_status { get; set; }
        public Nullable<int> all_madeby { get; set; }
        public Nullable<int> all_modifyby { get; set; }
        public Nullable<System.DateTime> all_date_created { get; set; }
        public Nullable<System.DateTime> all_date_modified { get; set; }
        public string all_type { get; set; }
        public string all_severity { get; set; }
    }
}
