//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Amity_Reimb
    {
        public int car_Id { get; set; }
        public Nullable<int> car_appId { get; set; }
        public string car_checkbox { get; set; }
        public string car_e1 { get; set; }
        public string car_e2 { get; set; }
        public string car_e3 { get; set; }
        public string car_e4 { get; set; }
        public string car_e5 { get; set; }
        public string car_e6 { get; set; }
        public string car_e7 { get; set; }
        public string car_e8 { get; set; }
        public string car_e9 { get; set; }
        public string car_e10 { get; set; }
        public string car_e11 { get; set; }
        public string car_e12 { get; set; }
        public string car_e13 { get; set; }
        public Nullable<System.DateTime> car_d1 { get; set; }
        public Nullable<System.DateTime> car_d2 { get; set; }
        public Nullable<System.DateTime> car_date_created { get; set; }
        public Nullable<System.DateTime> car_date_modified { get; set; }
        public string car_status { get; set; }
        public Nullable<int> car_madeby { get; set; }
        public Nullable<int> car_modifyby { get; set; }
    }
}
