//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_APPOINTMENTS_STATUS
    {
        public int apsId { get; set; }
        public string aps_status { get; set; }
        public string aps_color { get; set; }
        public Nullable<int> aps_madeby { get; set; }
        public string aps_activity_status { get; set; }
        public Nullable<System.DateTime> aps_date_created { get; set; }
        public Nullable<System.DateTime> aps_date_modified { get; set; }
    }
}
