//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Appointments_Package
    {
        public int apsId { get; set; }
        public Nullable<int> aps_appId { get; set; }
        public Nullable<int> aps_patId { get; set; }
        public Nullable<int> aps_invId { get; set; }
        public Nullable<int> aps_ptId { get; set; }
        public Nullable<int> aps_qty { get; set; }
        public Nullable<int> aps_used { get; set; }
        public Nullable<int> aps_balance { get; set; }
        public Nullable<int> aps_services { get; set; }
        public Nullable<int> aps_package { get; set; }
        public string aps_status { get; set; }
        public Nullable<int> aps_madeby { get; set; }
        public Nullable<System.DateTime> aps_date_created { get; set; }
    }
}
