//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_APP_REMARKS
    {
        public int arId { get; set; }
        public Nullable<int> ar_appId { get; set; }
        public Nullable<int> ar_employee { get; set; }
        public string ar_remarks { get; set; }
        public Nullable<System.DateTime> ar_date_created { get; set; }
        public Nullable<int> ar_patId { get; set; }
        public Nullable<System.DateTime> ar_fllowupdate { get; set; }
    }
}
