//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AppJourney
    {
        public int AJId { get; set; }
        public Nullable<int> AJ_AJCId { get; set; }
        public Nullable<int> AJ_AJSCId { get; set; }
        public Nullable<int> AJ_AppId { get; set; }
        public Nullable<int> AJ_PatId { get; set; }
        public string AJ_Status { get; set; }
        public Nullable<bool> AJ_isCompleted { get; set; }
        public Nullable<System.DateTime> AJ_Timestamp { get; set; }
    }
}
