//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AppJourney_SubCategory
    {
        public int AJSCId { get; set; }
        public Nullable<int> AJSC_Order { get; set; }
        public Nullable<int> AJSC_AJCId { get; set; }
        public string AJSC_Value { get; set; }
        public string AJSC_Status { get; set; }
    }
}
