//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ARAB_ORIENT_NEW
    {
        public int caonId { get; set; }
        public Nullable<int> caon_appId { get; set; }
        public string caon_1 { get; set; }
        public string caon_2 { get; set; }
        public string caon_3 { get; set; }
        public string caon_4 { get; set; }
        public string caon_5 { get; set; }
        public string caon_6 { get; set; }
        public string caon_7 { get; set; }
        public string caon_8 { get; set; }
        public string caon_9 { get; set; }
        public string caon_10 { get; set; }
        public string caon_11 { get; set; }
        public string caon_12 { get; set; }
        public string caon_13 { get; set; }
        public string caon_14 { get; set; }
        public string caon_15 { get; set; }
        public string caon_16 { get; set; }
        public string caon_17 { get; set; }
        public string caon_18 { get; set; }
        public string caon_19 { get; set; }
        public string caon_20 { get; set; }
        public string caon_21 { get; set; }
        public Nullable<System.DateTime> caon_22 { get; set; }
        public string caon_chk { get; set; }
        public string caon_status { get; set; }
        public Nullable<int> caon_madeby { get; set; }
        public Nullable<int> caon_modifyby { get; set; }
        public Nullable<System.DateTime> caon_date_created { get; set; }
        public Nullable<System.DateTime> caon_date_modified { get; set; }
    }
}
