//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ARR_FORM
    {
        public int carr_Id { get; set; }
        public Nullable<int> carr_appId { get; set; }
        public string carr_e1 { get; set; }
        public string carr_e2 { get; set; }
        public string carr_e3 { get; set; }
        public string carr_e4 { get; set; }
        public string carr_e5 { get; set; }
        public string carr_e6 { get; set; }
        public string carr_e7 { get; set; }
        public string carr_checkbox { get; set; }
        public Nullable<int> carr_madeby { get; set; }
        public Nullable<System.DateTime> carr_date_created { get; set; }
        public Nullable<System.DateTime> carr_date_modified { get; set; }
        public string carr_status { get; set; }
        public Nullable<System.DateTime> carr_date { get; set; }
        public string carr_other { get; set; }
    }
}
