//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ConsultationEMR_Maintemplate
    {
        public int cemtId { get; set; }
        public string cemt_type { get; set; }
        public string cemt_name { get; set; }
        public string cemt_status { get; set; }
        public Nullable<int> cemt_madeby { get; set; }
        public Nullable<System.DateTime> cemt_date_created { get; set; }
        public string cemt_type2 { get; set; }
    }
}
