//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CommunicationMedia_Settings
    {
        public int CMSId { get; set; }
        public Nullable<int> CMS_CMId { get; set; }
        public string CMS_Type { get; set; }
        public Nullable<int> CMS_UserId { get; set; }
        public Nullable<bool> CMS_Status { get; set; }
    }
}
