//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ConsultationEMR_Appointment
    {
        public int cemrId { get; set; }
        public Nullable<int> cemr_cemtId { get; set; }
        public Nullable<int> cemr_appId { get; set; }
        public Nullable<int> cemr_patId { get; set; }
        public string cemr_complaint { get; set; }
        public string cemr_pasthistory { get; set; }
        public string cemr_checkvalue { get; set; }
        public string cemr_mentalorianted { get; set; }
        public string cemr_mentaldisoriented { get; set; }
        public string cemr_mentalimpired { get; set; }
        public string cemr_acute1 { get; set; }
        public string cemr_subacute { get; set; }
        public string cemr_chronic { get; set; }
        public string cemr_recurrent { get; set; }
        public string cemr_durationin { get; set; }
        public string cemr_gettingworse { get; set; }
        public string cemr_better { get; set; }
        public string cemr_stillsame { get; set; }
        public string cemr_bodyparts { get; set; }
        public string cemr_observationins { get; set; }
        public string cemr_palpation { get; set; }
        public string cemr_rom { get; set; }
        public string cemr_mptest { get; set; }
        public string cemr_stest { get; set; }
        public string cemr_reflexes { get; set; }
        public string cemr_dermatone { get; set; }
        public string cemr_myotome { get; set; }
        public string cemr_independent { get; set; }
        public string cemr_dependent { get; set; }
        public string cemr_crutches { get; set; }
        public string cemr_walker { get; set; }
        public string cemr_wheelchair { get; set; }
        public string cemr_active { get; set; }
        public string cemr_athlete { get; set; }
        public string cemr_lifestyle { get; set; }
        public string cemr_bedridden { get; set; }
        public string cemr_radiology { get; set; }
        public string cemr_procedure { get; set; }
        public string cemr_stgoals { get; set; }
        public string cemr_ltgoals { get; set; }
        public string cemr_followup { get; set; }
        public string cemr_session { get; set; }
        public string cemr_treatpoints { get; set; }
        public string cemr_management { get; set; }
        public string cemr_status { get; set; }
        public Nullable<int> cemr_madeby { get; set; }
        public Nullable<System.DateTime> cemr_date_created { get; set; }
    }
}
