//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_COMPLAINTS_MASTER
    {
        public int cmId { get; set; }
        public string cm_title { get; set; }
        public string cm_desc { get; set; }
        public Nullable<int> cm_madeby { get; set; }
        public string cm_status { get; set; }
        public Nullable<System.DateTime> cm_date_created { get; set; }
        public Nullable<System.DateTime> cm_date_modified { get; set; }
    }
}
