//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ControlledDrugs_Prescription
    {
        public int precId { get; set; }
        public int prec_appId { get; set; }
        public int prec_empId { get; set; }
        public int prec_medicine { get; set; }
        public string prec_instr { get; set; }
        public string prec_type { get; set; }
        public Nullable<double> prec_qty { get; set; }
        public string prec_qtype { get; set; }
        public string prec_duration { get; set; }
        public string prec_temp1 { get; set; }
        public string prec_temp2 { get; set; }
        public string prec_temp3 { get; set; }
        public string prec_temp4 { get; set; }
        public string prec_temp5 { get; set; }
        public string prec_temp6 { get; set; }
        public string prec_status { get; set; }
        public string prec_oj_type { get; set; }
        public string prec_oj_code { get; set; }
    }
}
