//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ConsultationEMR_Apptemplate
    {
        public int ceatId { get; set; }
        public Nullable<int> ceatId_cemtId { get; set; }
        public Nullable<int> ceatId_appId { get; set; }
        public string ceat_status { get; set; }
        public Nullable<int> ceat_madeby { get; set; }
        public Nullable<System.DateTime> ceat_date_created { get; set; }
    }
}
