//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ControlledDrugs_Prescription_Tracking
    {
        public int prectId { get; set; }
        public int precId { get; set; }
        public int prect_appId { get; set; }
        public string prec_oj_type { get; set; }
        public string prec_oj_code { get; set; }
        public string prec_oj_response { get; set; }
        public Nullable<System.DateTime> pres_oj_datetime { get; set; }
    }
}
