//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Colposcopy_Referral_New
    {
        public int crnId { get; set; }
        public Nullable<int> crn_appId { get; set; }
        public string crn_1 { get; set; }
        public string crn_2 { get; set; }
        public string crn_3 { get; set; }
        public string crn_radio1 { get; set; }
        public Nullable<System.DateTime> crn_date1 { get; set; }
        public Nullable<System.DateTime> crn_date2 { get; set; }
        public Nullable<System.DateTime> crn_date3 { get; set; }
        public Nullable<System.DateTime> crn_date4 { get; set; }
        public Nullable<System.DateTime> crn_date5 { get; set; }
        public Nullable<System.DateTime> crn_date6 { get; set; }
        public Nullable<System.DateTime> crn_date7 { get; set; }
        public Nullable<System.DateTime> crn_date8 { get; set; }
        public Nullable<System.DateTime> crn_date9 { get; set; }
        public Nullable<System.DateTime> crn_time1 { get; set; }
        public string crn_status { get; set; }
        public Nullable<int> crn_made_by { get; set; }
        public Nullable<System.DateTime> crn_date_created { get; set; }
        public Nullable<int> crn_modified_by { get; set; }
        public Nullable<System.DateTime> crn_date_modified { get; set; }
    }
}
