//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CPT_TOOTHS_CATEGORY
    {
        public int ctcyId { get; set; }
        public string ctcy_code { get; set; }
        public string ctcy_category { get; set; }
    }
}
