//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CPT_TOOTHS
    {
        public int cctId { get; set; }
        public string cct_code { get; set; }
        public string cct_category { get; set; }
        public Nullable<System.DateTime> cct_date_created { get; set; }
        public Nullable<System.DateTime> cct_date_modified { get; set; }
        public Nullable<bool> cct_flagdeleted { get; set; }
        public string cct_sub_category { get; set; }
        public string cct_status { get; set; }
        public Nullable<int> cct_madeby { get; set; }
    }
}
