//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CPT_ITEMS
    {
        public int cptId { get; set; }
        public string cpt_code { get; set; }
        public string cpt_item { get; set; }
        public Nullable<double> cpt_qty { get; set; }
        public string cpt_uom { get; set; }
        public Nullable<int> cpt_madeby { get; set; }
        public System.DateTime cpt_date_created { get; set; }
        public System.DateTime cpt_date_modified { get; set; }
    }
}
