//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CURRENCY
    {
        public int curId { get; set; }
        public string cur_country { get; set; }
        public string cur_currency { get; set; }
        public string cur_code { get; set; }
    }
}
