//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DERMA_NOTES
    {
        public int dnId { get; set; }
        public int dn_appId { get; set; }
        public string dn_notes { get; set; }
        public string dn_status { get; set; }
        public Nullable<int> dn_madeby { get; set; }
        public Nullable<int> dn_modifyby { get; set; }
        public Nullable<System.DateTime> dn_date_created { get; set; }
        public Nullable<System.DateTime> dn_date_modified { get; set; }
    }
}
