//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DENTAL_PERIO_CHART
    {
        public int perioId { get; set; }
        public Nullable<int> perio_appId { get; set; }
        public string perio_tooths { get; set; }
        public Nullable<System.DateTime> perio_date_created { get; set; }
        public Nullable<System.DateTime> perio_date_modified { get; set; }
        public string perio_status { get; set; }
        public Nullable<int> perio_madeby { get; set; }
    }
}
