//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Dental_External_Form_Consent
    {
        public int cde_Id { get; set; }
        public Nullable<int> cde_appId { get; set; }
        public string cde_check1 { get; set; }
        public string cde_text1 { get; set; }
        public string cde_text2 { get; set; }
        public string cde_image { get; set; }
        public string cde_status { get; set; }
        public Nullable<int> cde_made_by { get; set; }
        public Nullable<System.DateTime> cde_date_created { get; set; }
        public Nullable<int> cde_modified_by { get; set; }
        public Nullable<System.DateTime> cde_date_modified { get; set; }
    }
}
