//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DHA_REPORTS
    {
        public int dha_Id { get; set; }
        public Nullable<int> dha_InptCode { get; set; }
        public string dha_InptType { get; set; }
        public Nullable<int> dha_IdtypeCode { get; set; }
        public string dha_IdType { get; set; }
        public Nullable<int> dha_genderCode { get; set; }
        public string dha_gender { get; set; }
        public Nullable<int> Dha_gccCode { get; set; }
        public string dha_gccName { get; set; }
        public Nullable<int> dha_emirateCode { get; set; }
        public string dha_emirateName { get; set; }
        public Nullable<int> dha_specalityCode { get; set; }
        public string dha_specality { get; set; }
    }
}
