//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Dmax_Mesotherapy_Consent
    {
        public int dmcId { get; set; }
        public Nullable<int> dmc_appId { get; set; }
        public string dmc_1 { get; set; }
        public string dmc_status { get; set; }
        public Nullable<int> dmc_made_by { get; set; }
        public Nullable<System.DateTime> dmc_date_created { get; set; }
        public Nullable<int> dmc_modified_by { get; set; }
        public Nullable<System.DateTime> dmc_date_modified { get; set; }
    }
}
