//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Dmax_Genius
    {
        public int cdgId { get; set; }
        public Nullable<int> cdg_appId { get; set; }
        public string cdg_1 { get; set; }
        public string cdg_status { get; set; }
        public Nullable<int> cdg_made_by { get; set; }
        public Nullable<System.DateTime> cdg_date_created { get; set; }
        public Nullable<int> cdg_modified_by { get; set; }
        public Nullable<System.DateTime> cdg_date_modified { get; set; }
    }
}
