//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Dmax_Filler
    {
        public int cdfId { get; set; }
        public Nullable<int> cdf_appId { get; set; }
        public string cdf_1 { get; set; }
        public string cdf_status { get; set; }
        public Nullable<int> cdf_made_by { get; set; }
        public Nullable<System.DateTime> cdf_date_created { get; set; }
        public Nullable<int> cdf_modified_by { get; set; }
        public Nullable<System.DateTime> cdf_date_modified { get; set; }
    }
}
