//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Dmax_Laser_Treatment
    {
        public int dltId { get; set; }
        public Nullable<int> dlt_appId { get; set; }
        public string dlt_1 { get; set; }
        public string dlt_status { get; set; }
        public Nullable<int> dlt_made_by { get; set; }
        public Nullable<System.DateTime> dlt_date_created { get; set; }
        public Nullable<int> dlt_modified_by { get; set; }
        public Nullable<System.DateTime> dlt_date_modified { get; set; }
    }
}
