//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Dmax_Fractional_Laser
    {
        public int dfcId { get; set; }
        public Nullable<int> dfc_appId { get; set; }
        public string dfc_1 { get; set; }
        public string dfc_status { get; set; }
        public Nullable<int> dfc_made_by { get; set; }
        public Nullable<System.DateTime> dfc_date_created { get; set; }
        public Nullable<int> dfc_modified_by { get; set; }
        public Nullable<System.DateTime> dfc_date_modified { get; set; }
    }
}
