//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Dmax_Botox
    {
        public int cdbId { get; set; }
        public Nullable<int> cdb_appId { get; set; }
        public string cdb_1 { get; set; }
        public string cdb_status { get; set; }
        public Nullable<int> cdb_made_by { get; set; }
        public Nullable<System.DateTime> cdb_date_created { get; set; }
        public Nullable<int> cdb_modified_by { get; set; }
        public Nullable<System.DateTime> cdb_date_modified { get; set; }
    }
}
