//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Dmax_Thread_Lifting
    {
        public int dtlId { get; set; }
        public Nullable<int> dtl_appId { get; set; }
        public string dtl_1 { get; set; }
        public string dtl_status { get; set; }
        public Nullable<int> dtl_made_by { get; set; }
        public Nullable<System.DateTime> dtl_date_created { get; set; }
        public Nullable<int> dtl_modified_by { get; set; }
        public Nullable<System.DateTime> dtl_date_modified { get; set; }
    }
}
