//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Dmax_Hydrafacial_Treatment
    {
        public int dhtId { get; set; }
        public Nullable<int> dht_appId { get; set; }
        public string dht_1 { get; set; }
        public string dht_status { get; set; }
        public Nullable<int> dht_made_by { get; set; }
        public Nullable<System.DateTime> dht_date_created { get; set; }
        public Nullable<int> dht_modified_by { get; set; }
        public Nullable<System.DateTime> dht_date_modified { get; set; }
    }
}
