//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Dmax_Crown_Bridge
    {
        public int cdcbId { get; set; }
        public Nullable<int> cdcb_appId { get; set; }
        public string cdcb_1 { get; set; }
        public string cdcb_2 { get; set; }
        public string cdcb_3 { get; set; }
        public string cdcb_4 { get; set; }
        public string cdcb_status { get; set; }
        public Nullable<int> cdcb_made_by { get; set; }
        public Nullable<System.DateTime> cdcb_date_created { get; set; }
        public Nullable<int> cdcb_modified_by { get; set; }
        public Nullable<System.DateTime> cdcb_date_modified { get; set; }
    }
}
