//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Dmax_Informed_Consent
    {
        public int dicId { get; set; }
        public Nullable<int> dic_appId { get; set; }
        public string dic_1 { get; set; }
        public string dic_2 { get; set; }
        public Nullable<System.DateTime> dic_date { get; set; }
        public string dic_status { get; set; }
        public Nullable<int> dic_made_by { get; set; }
        public Nullable<System.DateTime> dic_date_created { get; set; }
        public Nullable<int> dic_modified_by { get; set; }
        public Nullable<System.DateTime> dic_date_modified { get; set; }
    }
}
