//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_EAR_MICROSCOPY_REPORT
    {
        public int emrId { get; set; }
        public Nullable<int> emr_appId { get; set; }
        public string emr_notes { get; set; }
        public Nullable<int> emr_madeby { get; set; }
        public string emr_status { get; set; }
        public Nullable<System.DateTime> emr_date_created { get; set; }
        public Nullable<System.DateTime> emr_date_modified { get; set; }
    }
}
