//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_EMPLOYEE_MESSAGES
    {
        public int cmeId { get; set; }
        public Nullable<System.DateTime> cme_StartDateTime { get; set; }
        public Nullable<System.DateTime> cme_EndDateTime { get; set; }
        public Nullable<int> cme_EmployeeFrom { get; set; }
        public string cme_EmployeeTo { get; set; }
        public string cme_message { get; set; }
        public string cme_status { get; set; }
        public Nullable<System.DateTime> cme_date_created { get; set; }
        public Nullable<System.DateTime> cme_date_modified { get; set; }
    }
}
