//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_EMP_LOGGEDIN_TIME
    {
        public int eltId { get; set; }
        public Nullable<int> elt_empId { get; set; }
        public string elt_type { get; set; }
        public Nullable<System.DateTime> elt_date_time { get; set; }
    }
}
