//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Employees_Login
    {
        public int empId { get; set; }
        public string el_username { get; set; }
        public string el_key1 { get; set; }
        public string el_key2 { get; set; }
        public string el_recoverCode { get; set; }
        public string el_recoverEmail { get; set; }
        public Nullable<int> el_madeBy { get; set; }
        public string el_status { get; set; }
        public Nullable<System.DateTime> el_createdDateTime { get; set; }
        public Nullable<System.DateTime> el_modifiedDateTime { get; set; }
        public Nullable<int> el_passwordValidity { get; set; }
        public Nullable<bool> el_resetStatus { get; set; }
        public Nullable<System.DateTime> el_resetRequestTimeStamp { get; set; }
        public Nullable<System.DateTime> el_lastResetsTimeStamp { get; set; }
    }
}
