//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_EMPLOYEES_ROASTER
    {
        public int erId { get; set; }
        public Nullable<int> er_employee { get; set; }
        public Nullable<int> er_branch { get; set; }
        public string er_day { get; set; }
        public Nullable<int> er_ftime { get; set; }
        public Nullable<int> er_ttime { get; set; }
        public string er_status { get; set; }
        public string er_type { get; set; }
        public string er_range { get; set; }
        public string er_round { get; set; }
        public Nullable<System.DateTime> er_fdate { get; set; }
        public Nullable<System.DateTime> er_tdate { get; set; }
        public Nullable<System.DateTime> er_date_created { get; set; }
        public Nullable<System.DateTime> er_date_modified { get; set; }
    }
}
