//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_EMPLOYEES
    {
        public int empId { get; set; }
        public string emp_login { get; set; }
        public string emp_pass { get; set; }
        public string emp_name { get; set; }
        public Nullable<int> emp_dept { get; set; }
        public Nullable<int> emp_desig { get; set; }
        public string emp_gender { get; set; }
        public Nullable<int> emp_nat { get; set; }
        public string emp_tel { get; set; }
        public string emp_mob { get; set; }
        public string emp_fax { get; set; }
        public string emp_email { get; set; }
        public string emp_address { get; set; }
        public string emp_license { get; set; }
        public Nullable<double> emp_comm { get; set; }
        public Nullable<decimal> emp_col { get; set; }
        public Nullable<int> emp_branch { get; set; }
        public string emp_photo { get; set; }
        public string emp_teeth { get; set; }
        public Nullable<int> emp_rank { get; set; }
        public string emp_work_branch { get; set; }
        public string emp_color { get; set; }
        public string emp_desig_name { get; set; }
        public string emp_dept_name { get; set; }
        public Nullable<int> emp_madeby { get; set; }
        public Nullable<int> emp_modifyby { get; set; }
        public string emp_account { get; set; }
        public string emp_account1 { get; set; }
        public string emp_account2 { get; set; }
        public string emp_account3 { get; set; }
        public string emp_sign { get; set; }
        public string emp_stamp { get; set; }
        public Nullable<double> emp_consultation_commi { get; set; }
        public Nullable<double> emp_procedure_commi { get; set; }
        public Nullable<double> emp_lab_commi { get; set; }
        public Nullable<double> emp_rad_commi { get; set; }
        public Nullable<double> emp_pha_commi { get; set; }
        public Nullable<double> emp_met_commi { get; set; }
        public string emp_speciality { get; set; }
        public string emp_dha_login { get; set; }
        public string emp_dha_pass { get; set; }
        public string emp_lname { get; set; }
        public Nullable<double> emp_disc_allowed { get; set; }
        public string emp_whatsappId { get; set; }
        public string emp_dha_speciality { get; set; }
        public string emp_status { get; set; }
        public Nullable<System.DateTime> emp_date_created { get; set; }
        public Nullable<System.DateTime> emp_date_modified { get; set; }
        public System.DateTime emp_pwdExpiry_date { get; set; }
    }
}
