//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ENQ_SOURCE
    {
        public int eqcId { get; set; }
        public Nullable<int> eqc_slno { get; set; }
        public string eqc_code { get; set; }
        public string eqc_title { get; set; }
        public Nullable<System.DateTime> eqc_start_date { get; set; }
        public Nullable<System.DateTime> eqc_end_date { get; set; }
        public string eqc_status { get; set; }
        public Nullable<int> eqc_madeby { get; set; }
        public Nullable<System.DateTime> eqc_date_created { get; set; }
        public Nullable<System.DateTime> eqc_date_modified { get; set; }
    }
}
