//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_EXTRA_ORAL
    {
        public int ceoId { get; set; }
        public Nullable<int> ceo_appId { get; set; }
        public string ceo_1 { get; set; }
        public string ceo_2 { get; set; }
        public string ceo_3 { get; set; }
        public string ceo_4 { get; set; }
        public string ceo_5 { get; set; }
        public string ceo_6 { get; set; }
        public string ceo_7 { get; set; }
        public string ceo_8 { get; set; }
        public string ceo_9 { get; set; }
        public string ceo_10 { get; set; }
        public string ceo_11 { get; set; }
        public Nullable<System.DateTime> ceo_date_created { get; set; }
        public Nullable<System.DateTime> ceo_date_modified { get; set; }
        public string ceo_12 { get; set; }
        public Nullable<int> ceo_madeby { get; set; }
        public string ceo_status { get; set; }
    }
}
