//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_FIBREOPTIC_LARYNGOSCOPY_REPORT
    {
        public int flrId { get; set; }
        public Nullable<int> flr_appId { get; set; }
        public string flr_notes { get; set; }
        public Nullable<int> flr_madeby { get; set; }
        public string flr_status { get; set; }
        public Nullable<System.DateTime> flr_date_created { get; set; }
        public Nullable<System.DateTime> flr_date_modified { get; set; }
    }
}
