//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_GENERAL_CONSENT_FORM
    {
        public int gcfId { get; set; }
        public Nullable<int> gcf_appId { get; set; }
        public Nullable<System.DateTime> gcf_date_created { get; set; }
        public Nullable<System.DateTime> gcf_date_modified { get; set; }
    }
}
