//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_General_Prescriptions
    {
        public int gpreId { get; set; }
        public int gpre_appId { get; set; }
        public string gpre_desc { get; set; }
        public string gpre_status { get; set; }
        public Nullable<int> gpre_madeby { get; set; }
        public Nullable<int> gpre_modifiedby { get; set; }
        public Nullable<System.DateTime> gpre_date_created { get; set; }
        public Nullable<System.DateTime> gpre_date_modified { get; set; }
    }
}
