//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_GULFCARE_NEW
    {
        public int gucnId { get; set; }
        public Nullable<int> gucn_appId { get; set; }
        public string gucn_1 { get; set; }
        public string gucn_2 { get; set; }
        public string gucn_3 { get; set; }
        public string gucn_4 { get; set; }
        public string gucn_5 { get; set; }
        public string gucn_6 { get; set; }
        public string gucn_7 { get; set; }
        public string gucn_8 { get; set; }
        public string gucn_9 { get; set; }
        public string gucn_10 { get; set; }
        public string gucn_11 { get; set; }
        public string gucn_12 { get; set; }
        public string gucn_13 { get; set; }
        public string gucn_14 { get; set; }
        public string gucn_15 { get; set; }
        public string gucn_16 { get; set; }
        public string gucn_17 { get; set; }
        public string gucn_18 { get; set; }
        public string gucn_19 { get; set; }
        public string gucn_20 { get; set; }
        public string gucn_21 { get; set; }
        public string gucn_22 { get; set; }
        public string gucn_23 { get; set; }
        public string gucn_24 { get; set; }
        public string gucn_25 { get; set; }
        public string gucn_26 { get; set; }
        public string gucn_27 { get; set; }
        public string gucn_28 { get; set; }
        public string gucn_29 { get; set; }
        public string gucn_30 { get; set; }
        public string gucn_31 { get; set; }
        public string gucn_32 { get; set; }
        public string gucn_33 { get; set; }
        public string gucn_34 { get; set; }
        public string gucn_35 { get; set; }
        public string gucn_36 { get; set; }
        public string gucn_37 { get; set; }
        public string gucn_38 { get; set; }
        public string gucn_39 { get; set; }
        public string gucn_40 { get; set; }
        public string gucn_41 { get; set; }
        public string gucn_42 { get; set; }
        public string gucn_43 { get; set; }
        public Nullable<int> gucn_modifyby { get; set; }
        public string gucn_checkbox { get; set; }
        public string gucn_status { get; set; }
        public Nullable<int> gucn_madeby { get; set; }
        public Nullable<System.DateTime> gucn_date_created { get; set; }
        public Nullable<System.DateTime> gucn_date_modified { get; set; }
    }
}
