//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_HARD_TISSUE
    {
        public int chtId { get; set; }
        public Nullable<int> cht_appId { get; set; }
        public string cht_1 { get; set; }
        public string cht_2 { get; set; }
        public string cht_3 { get; set; }
        public string cht_4 { get; set; }
        public string cht_5 { get; set; }
        public string cht_6 { get; set; }
        public string cht_7 { get; set; }
        public string cht_8 { get; set; }
        public string cht_9 { get; set; }
        public string cht_10 { get; set; }
        public string cht_11 { get; set; }
        public string cht_12 { get; set; }
        public string cht_13 { get; set; }
        public string cht_14 { get; set; }
        public string cht_15 { get; set; }
        public string cht_16 { get; set; }
        public string cht_17 { get; set; }
        public string cht_18 { get; set; }
        public Nullable<System.DateTime> cht_date_created { get; set; }
        public Nullable<System.DateTime> cht_date_modified { get; set; }
        public Nullable<int> cht_madeby { get; set; }
        public string cht_status { get; set; }
    }
}
