//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_HARD_TISSUETOOTH
    {
        public int chtdId { get; set; }
        public Nullable<int> chtd_appId { get; set; }
        public Nullable<int> chtd_chtId { get; set; }
        public string chtd_1 { get; set; }
        public string chtd_2 { get; set; }
        public string chtd_3 { get; set; }
        public string chtd_status { get; set; }
        public Nullable<int> chtd_madeby { get; set; }
        public Nullable<System.DateTime> chtd_date_created { get; set; }
        public Nullable<System.DateTime> chtd_date_modified { get; set; }
    }
}
