//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_HEALTH_INT_NEW
    {
        public int chinId { get; set; }
        public Nullable<int> chin_appId { get; set; }
        public string chin_1 { get; set; }
        public string chin_2 { get; set; }
        public string chin_3 { get; set; }
        public string chin_4 { get; set; }
        public string chin_5 { get; set; }
        public string chin_6 { get; set; }
        public string chin_7 { get; set; }
        public string chin_8 { get; set; }
        public string chin_9 { get; set; }
        public string chin_10 { get; set; }
        public string chin_11 { get; set; }
        public Nullable<System.DateTime> chin_date1 { get; set; }
        public Nullable<System.DateTime> chin_date2 { get; set; }
        public Nullable<System.DateTime> chin_date3 { get; set; }
        public string chin_checkbox { get; set; }
        public string chin_status { get; set; }
        public Nullable<int> chin_madeby { get; set; }
        public Nullable<int> chin_modifyby { get; set; }
        public Nullable<System.DateTime> chin_date_created { get; set; }
        public Nullable<System.DateTime> chin_date_modified { get; set; }
    }
}
