//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Health_Declaration
    {
        public int chd_Id { get; set; }
        public Nullable<int> chd_appId { get; set; }
        public string chd_checkbox { get; set; }
        public string chd_Prob1 { get; set; }
        public string chd_Prob2 { get; set; }
        public string chd_Prob3 { get; set; }
        public Nullable<System.DateTime> chd_date_created { get; set; }
        public Nullable<System.DateTime> chd_date_modified { get; set; }
        public string chd_status { get; set; }
        public string chd_Prob4 { get; set; }
        public string chd_Prob5 { get; set; }
        public Nullable<int> chd_madeby { get; set; }
    }
}
