//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ImageComparision_Uploaded
    {
        public int imgcId { get; set; }
        public Nullable<int> imgc_patId { get; set; }
        public Nullable<int> imgc_appId { get; set; }
        public string imgc_notes { get; set; }
        public string imgc_image { get; set; }
        public string imgc_type { get; set; }
        public string imgc_status { get; set; }
        public Nullable<int> imgc_made_by { get; set; }
        public Nullable<System.DateTime> imgc_date_created { get; set; }
    }
}
