//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_INSURANCE_PAYER_NOTES
    {
        public int ipnId { get; set; }
        public Nullable<int> ipn_ip_ins { get; set; }
        public string ipn_notes { get; set; }
        public string ipn_doc_title { get; set; }
        public string ipn_document { get; set; }
        public string ipn_path { get; set; }
        public string ipn_status { get; set; }
        public Nullable<int> ipn_madeby { get; set; }
        public Nullable<System.DateTime> ipn_date_created { get; set; }
    }
}
