//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_INSURANCE_SCHEMES
    {
        public int isId { get; set; }
        public Nullable<int> is_insurance { get; set; }
        public string is_title { get; set; }
        public Nullable<double> is_copay { get; set; }
        public Nullable<double> is_dcopay { get; set; }
        public Nullable<double> is_hp_dcopay { get; set; }
        public Nullable<double> is_ip_dcopay { get; set; }
        public string is_copay_type { get; set; }
        public string is_dcopay_type { get; set; }
        public string is_ip_dcopay_type { get; set; }
        public string is_hp_dcopay_type { get; set; }
        public Nullable<double> is_cded { get; set; }
        public string is_cded_type { get; set; }
        public Nullable<double> is_dded { get; set; }
        public string is_dded_type { get; set; }
        public Nullable<double> is_pded { get; set; }
        public string is_pded_type { get; set; }
        public Nullable<double> is_lded { get; set; }
        public string is_lded_type { get; set; }
        public Nullable<double> is_rded { get; set; }
        public string is_rded_type { get; set; }
        public Nullable<double> is_mded { get; set; }
        public string is_mded_type { get; set; }
        public Nullable<int> is_icId { get; set; }
        public string is_ic_code { get; set; }
        public string is_ic_name { get; set; }
        public string is_ip_code { get; set; }
        public string is_ip_name { get; set; }
        public Nullable<double> is_copay_limit { get; set; }
        public Nullable<double> is_dcopay_limit { get; set; }
        public Nullable<double> is_hp_dcopay_limit { get; set; }
        public Nullable<double> is_ip_dcopay_limit { get; set; }
        public Nullable<double> is_cded_limit { get; set; }
        public Nullable<double> is_dded_limit { get; set; }
        public Nullable<double> is_pded_limit { get; set; }
        public Nullable<double> is_lded_limit { get; set; }
        public Nullable<double> is_rded_limit { get; set; }
        public Nullable<double> is_mded_limit { get; set; }
        public Nullable<double> is_allowed_limit { get; set; }
    }
}
