//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_INTERNAL_REFERAL
    {
        public int irefId { get; set; }
        public Nullable<int> iref_appId_from { get; set; }
        public Nullable<int> iref_appId_to { get; set; }
        public Nullable<int> iref_doctor_from { get; set; }
        public Nullable<int> iref_doctor_to { get; set; }
        public Nullable<System.DateTime> iref_date { get; set; }
        public Nullable<System.DateTime> iref_date_created { get; set; }
        public Nullable<System.DateTime> iref_date_modified { get; set; }
    }
}
