//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_INSURANCE_COMPANIES
    {
        public int icId { get; set; }
        public string ic_name { get; set; }
        public string ic_cperson { get; set; }
        public string ic_code { get; set; }
        public Nullable<decimal> ic_discount { get; set; }
        public string ic_tel { get; set; }
        public string ic_fax { get; set; }
        public string ic_email { get; set; }
        public string ic_url { get; set; }
        public string ic_pobox { get; set; }
        public string ic_address { get; set; }
        public string ic_city { get; set; }
        public Nullable<int> ic_country { get; set; }
        public string ic_notes { get; set; }
        public string ic_account { get; set; }
        public Nullable<decimal> ic_credit { get; set; }
        public Nullable<int> ic_topup { get; set; }
        public Nullable<int> ic_parent { get; set; }
        public Nullable<decimal> ic_share { get; set; }
        public string ic_type { get; set; }
        public Nullable<decimal> ic_obal { get; set; }
        public string ic_obal_type { get; set; }
        public Nullable<int> ic_branch { get; set; }
        public string ic_status { get; set; }
        public System.DateTime ic_date_created { get; set; }
        public System.DateTime ic_date_modified { get; set; }
        public Nullable<int> ic_madeby { get; set; }
        public Nullable<int> ic_modifiedby { get; set; }
    }
}
