//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_INSURANCE_NOTES
    {
        public int inId { get; set; }
        public Nullable<int> in_ins { get; set; }
        public string in_notes { get; set; }
        public string in_doc_title { get; set; }
        public string in_document { get; set; }
        public Nullable<int> in_madeby { get; set; }
        public Nullable<System.DateTime> in_date_created { get; set; }
    }
}
