//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Justification_Letter
    {
        public int jlId { get; set; }
        public Nullable<int> jl_madeby { get; set; }
        public Nullable<int> jl_appId { get; set; }
        public string jl_note { get; set; }
        public string jl_status { get; set; }
        public Nullable<System.DateTime> jl_date_created { get; set; }
        public Nullable<System.DateTime> jl_date_modified { get; set; }
        public Nullable<System.DateTime> jl_date { get; set; }
    }
}
