//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_KHAZANA_NEW
    {
        public int ckneId { get; set; }
        public Nullable<int> ckne_appId { get; set; }
        public string ckne_1 { get; set; }
        public string ckne_2 { get; set; }
        public string ckne_3 { get; set; }
        public string ckne_4 { get; set; }
        public string ckne_5 { get; set; }
        public string ckne_6 { get; set; }
        public string ckne_7 { get; set; }
        public string ckne_8 { get; set; }
        public string ckne_9 { get; set; }
        public string ckne_10 { get; set; }
        public string ckne_11 { get; set; }
        public string ckne_12 { get; set; }
        public string ckne_13 { get; set; }
        public string ckne_14 { get; set; }
        public string ckne_15 { get; set; }
        public string ckne_16 { get; set; }
        public string ckne_17 { get; set; }
        public string ckne_18 { get; set; }
        public string ckne_19 { get; set; }
        public string ckne_20 { get; set; }
        public string ckne_21 { get; set; }
        public string ckne_22 { get; set; }
        public string ckne_23 { get; set; }
        public string ckne_24 { get; set; }
        public string ckne_25 { get; set; }
        public string ckne_26 { get; set; }
        public string ckne_27 { get; set; }
        public string ckne_28 { get; set; }
        public string ckne_29 { get; set; }
        public string ckne_30 { get; set; }
        public string ckne_31 { get; set; }
        public string ckne_32 { get; set; }
        public string ckne_33 { get; set; }
        public string ckne_34 { get; set; }
        public string ckne_35 { get; set; }
        public Nullable<System.DateTime> ckne_date1 { get; set; }
        public Nullable<System.DateTime> ckne_date2 { get; set; }
        public string ckne_chk { get; set; }
        public string ckne_status { get; set; }
        public Nullable<int> ckne_madeby { get; set; }
        public Nullable<int> ckne_modifyby { get; set; }
        public Nullable<System.DateTime> ckne_date_created { get; set; }
        public Nullable<System.DateTime> ckne_date_modified { get; set; }
    }
}
