//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_LASER_FACE_MARKING
    {
        public int lfmId { get; set; }
        public Nullable<int> lfm_appId { get; set; }
        public Nullable<int> lfm_patId { get; set; }
        public string lfm_doc { get; set; }
        public Nullable<System.DateTime> lfm_date_created { get; set; }
        public Nullable<System.DateTime> lfm_date_modified { get; set; }
        public string lfm_form { get; set; }
        public string lfm_doc2 { get; set; }
        public string lfm_status { get; set; }
        public Nullable<int> lfm_madeby { get; set; }
    }
}
