//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Lab_Lonic_Codes
    {
        public int cllId { get; set; }
        public Nullable<int> cll_ptId { get; set; }
        public string cll_tr_code { get; set; }
        public string cll_code { get; set; }
        public string cll_name { get; set; }
        public string cll_result { get; set; }
        public string cll_units { get; set; }
        public string cll_status { get; set; }
        public Nullable<System.DateTime> cll_date_created { get; set; }
        public Nullable<System.DateTime> cll_date_modified { get; set; }
        public string cll_mrn { get; set; }
        public string cll_sdate { get; set; }
        public string cll_clinician { get; set; }
        public string cll_oclinician { get; set; }
    }
}
