//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Laser_Therapy_Sheet
    {
        public int ltsId { get; set; }
        public Nullable<int> lts_appId { get; set; }
        public Nullable<System.DateTime> lts_date { get; set; }
        public string lts_session { get; set; }
        public string lts_bodypart { get; set; }
        public string lts_skintype { get; set; }
        public string lts_flu_alex { get; set; }
        public string lts_flu_nd { get; set; }
        public string lts_remarks { get; set; }
        public string lts_offer { get; set; }
        public Nullable<System.DateTime> lts_date_created { get; set; }
        public Nullable<System.DateTime> lts_date_modified { get; set; }
        public Nullable<int> lts_madeby { get; set; }
        public string lts_status { get; set; }
    }
}
