//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Language_Progress_Form
    {
        public int lpfId { get; set; }
        public Nullable<int> lpf_appId { get; set; }
        public string lpf_1 { get; set; }
        public string lpf_2 { get; set; }
        public Nullable<System.DateTime> lpf_date1 { get; set; }
        public string lpf_3 { get; set; }
        public string lpf_4 { get; set; }
        public string lpf_5 { get; set; }
        public string lpf_chk1 { get; set; }
        public string lpf_6 { get; set; }
        public string lpf_7 { get; set; }
        public string lpf_8 { get; set; }
        public string lpf_9 { get; set; }
        public string lpf_10 { get; set; }
        public string lpf_11 { get; set; }
        public string lpf_12 { get; set; }
        public string lpf_13 { get; set; }
        public string lpf_radio1 { get; set; }
        public string lpf_radio2 { get; set; }
        public string lpf_radio3 { get; set; }
        public string lpf_radio4 { get; set; }
        public string lpf_14 { get; set; }
        public string lpf_15 { get; set; }
        public string lpf_16 { get; set; }
        public string lpf_17 { get; set; }
        public string lpf_18 { get; set; }
        public string lpf_19 { get; set; }
        public string lpf_20 { get; set; }
        public string lpf_21 { get; set; }
        public string lpf_22 { get; set; }
        public string lpf_23 { get; set; }
        public string lpf_24 { get; set; }
        public string lpf_25 { get; set; }
        public string lpf_26 { get; set; }
        public string lpf_27 { get; set; }
        public string lpf_28 { get; set; }
        public string lpf_29 { get; set; }
        public string lpf_30 { get; set; }
        public string lpf_31 { get; set; }
        public string lpf_32 { get; set; }
        public Nullable<int> lpf_made_by { get; set; }
        public string lpf_status { get; set; }
        public Nullable<int> lpf_modified_by { get; set; }
        public Nullable<System.DateTime> lpf_date_created { get; set; }
        public Nullable<System.DateTime> lpf_date_modified { get; set; }
    }
}
