//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Level2_Access
    {
        public int L2Id { get; set; }
        public Nullable<int> L1Id { get; set; }
        public string L2_Value { get; set; }
        public string L2_Status { get; set; }
    }
}
