//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MALAFFI_NABIDH_RIYATI_CODESETS
    {
        public int mnrId { get; set; }
        public string mnr_table { get; set; }
        public string mnr_codeset { get; set; }
        public string mnr_code { get; set; }
        public string mnr_description { get; set; }
        public string mnr_flag { get; set; }
    }
}
