//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MAPFRE_NEW
    {
        public int maprId { get; set; }
        public Nullable<int> mapr_appId { get; set; }
        public string mapr_1 { get; set; }
        public string mapr_2 { get; set; }
        public string mapr_3 { get; set; }
        public string mapr_4 { get; set; }
        public string mapr_5 { get; set; }
        public string mapr_6 { get; set; }
        public string mapr_7 { get; set; }
        public string mapr_8 { get; set; }
        public string mapr_9 { get; set; }
        public string mapr_10 { get; set; }
        public string mapr_11 { get; set; }
        public string mapr_12 { get; set; }
        public string mapr_13 { get; set; }
        public string mapr_14 { get; set; }
        public string mapr_15 { get; set; }
        public string mapr_16 { get; set; }
        public string mapr_17 { get; set; }
        public string mapr_18 { get; set; }
        public string mapr_19 { get; set; }
        public string mapr_20 { get; set; }
        public string mapr_chk { get; set; }
        public Nullable<System.DateTime> mapr_date1 { get; set; }
        public Nullable<System.DateTime> mapr_date2 { get; set; }
        public Nullable<System.DateTime> mapr_date3 { get; set; }
        public Nullable<System.DateTime> mapr_date4 { get; set; }
        public Nullable<System.DateTime> mapr_date5 { get; set; }
        public Nullable<System.DateTime> mapr_date6 { get; set; }
        public Nullable<System.DateTime> mapr_date7 { get; set; }
        public Nullable<System.DateTime> mapr_date8 { get; set; }
        public string mapr_status { get; set; }
        public Nullable<int> mapr_madeby { get; set; }
        public Nullable<int> mapr_modifyby { get; set; }
        public Nullable<System.DateTime> mapr_date_created { get; set; }
        public Nullable<System.DateTime> mapr_date_modified { get; set; }
    }
}
