//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MAXCARE_NEW
    {
        public int maxnId { get; set; }
        public Nullable<int> maxn_appId { get; set; }
        public string maxn_1 { get; set; }
        public string maxn_2 { get; set; }
        public string maxn_3 { get; set; }
        public string maxn_4 { get; set; }
        public string maxn_5 { get; set; }
        public string maxn_6 { get; set; }
        public string maxn_7 { get; set; }
        public string maxn_8 { get; set; }
        public string maxn_9 { get; set; }
        public string maxn_10 { get; set; }
        public string maxn_11 { get; set; }
        public string maxn_12 { get; set; }
        public string maxn_13 { get; set; }
        public string maxn_14 { get; set; }
        public string maxn_15 { get; set; }
        public string maxn_16 { get; set; }
        public string maxn_17 { get; set; }
        public string maxn_18 { get; set; }
        public string maxn_19 { get; set; }
        public string maxn_20 { get; set; }
        public string maxn_21 { get; set; }
        public string maxn_22 { get; set; }
        public string maxn_23 { get; set; }
        public string maxn_24 { get; set; }
        public string maxn_25 { get; set; }
        public string maxn_26 { get; set; }
        public string maxn_27 { get; set; }
        public string maxn_28 { get; set; }
        public string maxn_29 { get; set; }
        public string maxn_30 { get; set; }
        public string maxn_31 { get; set; }
        public string maxn_32 { get; set; }
        public string maxn_33 { get; set; }
        public string maxn_34 { get; set; }
        public string maxn_35 { get; set; }
        public string maxn_36 { get; set; }
        public string maxn_37 { get; set; }
        public string maxn_38 { get; set; }
        public string maxn_39 { get; set; }
        public string maxn_40 { get; set; }
        public string maxn_41 { get; set; }
        public string maxn_checkbox { get; set; }
        public Nullable<System.DateTime> maxn_date1 { get; set; }
        public Nullable<System.DateTime> maxn_date2 { get; set; }
        public Nullable<System.DateTime> maxn_date3 { get; set; }
        public string maxn_status { get; set; }
        public Nullable<int> maxn_madeby { get; set; }
        public Nullable<int> maxn_modifyby { get; set; }
        public Nullable<System.DateTime> maxn_date_created { get; set; }
        public Nullable<System.DateTime> maxn_date_modified { get; set; }
    }
}
