//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MED_NOTES
    {
        public int mnId { get; set; }
        public int mn_appId { get; set; }
        public string mn_notes { get; set; }
        public string mn_status { get; set; }
        public Nullable<int> mn_madeby { get; set; }
        public Nullable<int> mn_modifyby { get; set; }
        public Nullable<System.DateTime> mn_date_created { get; set; }
        public Nullable<System.DateTime> mn_date_modified { get; set; }
        public string mn_visitPlan { get; set; }
        public string mn_instructions { get; set; }
    }
}
