//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MEDNET_CLAIM_NEW
    {
        public int cmcnId { get; set; }
        public Nullable<int> cmcn_appId { get; set; }
        public string cmcn_1 { get; set; }
        public string cmcn_2 { get; set; }
        public string cmcn_3 { get; set; }
        public string cmcn_4 { get; set; }
        public string cmcn_5 { get; set; }
        public string cmcn_6 { get; set; }
        public string cmcn_7 { get; set; }
        public string cmcn_status { get; set; }
        public string cmcn_chk { get; set; }
        public Nullable<System.DateTime> cmcn_date1 { get; set; }
        public Nullable<System.DateTime> cmcn_date2 { get; set; }
        public Nullable<System.DateTime> cmcn_date3 { get; set; }
        public Nullable<int> cmcn_madeby { get; set; }
        public Nullable<int> cmcn_modifyby { get; set; }
        public Nullable<System.DateTime> cmcn_date_created { get; set; }
        public Nullable<System.DateTime> cmcn_date_modified { get; set; }
    }
}
