//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_METLIFE
    {
        public int metId { get; set; }
        public Nullable<int> met_appId { get; set; }
        public string met_check { get; set; }
        public string met_claim_amount { get; set; }
        public string met_currency { get; set; }
        public string met_1 { get; set; }
        public string met_2 { get; set; }
        public string met_3 { get; set; }
        public Nullable<System.DateTime> met_date_created { get; set; }
        public Nullable<System.DateTime> met_date_modified { get; set; }
        public Nullable<int> met_madeby { get; set; }
        public Nullable<int> met_modifyby { get; set; }
        public string met_status { get; set; }
        public Nullable<System.DateTime> met_4 { get; set; }
    }
}
