//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MEDICAL_DECISION
    {
        public int mdId { get; set; }
        public Nullable<int> md_appId { get; set; }
        public string md_txt1 { get; set; }
        public string md_txt2 { get; set; }
        public string md_txt3 { get; set; }
        public string md_txt4 { get; set; }
        public string md_txt5 { get; set; }
        public string md_txt6 { get; set; }
        public string md_txt7 { get; set; }
        public string md_chk { get; set; }
        public string md_status { get; set; }
        public Nullable<int> md_madeby { get; set; }
        public Nullable<System.DateTime> md_date_created { get; set; }
        public Nullable<System.DateTime> md_date_modified { get; set; }
    }
}
