//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MESSAGE_TYPE
    {
        public int mtId { get; set; }
        public string mt_type { get; set; }
        public string mt_status { get; set; }
        public Nullable<int> mt_branch { get; set; }
        public Nullable<int> mt_desig { get; set; }
        public Nullable<int> mt_emp { get; set; }
        public string mt_tat { get; set; }
        public Nullable<System.DateTime> mt_date_created { get; set; }
        public Nullable<System.DateTime> mt_date_modified { get; set; }
        public Nullable<int> mt_madeby { get; set; }
    }
}
