//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Medicines
    {
        public int itemId { get; set; }
        public Nullable<int> item_supplier { get; set; }
        public string item_type { get; set; }
        public string item_code { get; set; }
        public string item_name { get; set; }
        public Nullable<double> item_qty { get; set; }
        public string item_uom { get; set; }
        public string item_desc { get; set; }
        public string item_status { get; set; }
        public System.DateTime item_date_created { get; set; }
        public System.DateTime item_date_modified { get; set; }
        public string item_account { get; set; }
        public Nullable<int> item_category { get; set; }
        public Nullable<decimal> item_cost { get; set; }
        public Nullable<decimal> item_sprice { get; set; }
        public Nullable<System.DateTime> item_last_sold_date { get; set; }
        public Nullable<System.DateTime> item_last_purchase_date { get; set; }
        public Nullable<System.DateTime> item_last_order_date { get; set; }
        public string item_brand { get; set; }
        public string item_dosage { get; set; }
        public string item_strength { get; set; }
        public Nullable<int> item_location { get; set; }
        public Nullable<double> item_qty_adj { get; set; }
        public string item_pur_account { get; set; }
        public Nullable<int> item_branch { get; set; }
        public string item_si_code { get; set; }
        public Nullable<double> item_qty2 { get; set; }
        public string item_uom2 { get; set; }
        public Nullable<double> item_m_factor { get; set; }
        public Nullable<decimal> item_cost2 { get; set; }
        public Nullable<decimal> item_sprice2 { get; set; }
        public Nullable<decimal> item_vat { get; set; }
        public Nullable<double> item_qty3 { get; set; }
        public string item_uom3 { get; set; }
        public Nullable<double> item_m_factor2 { get; set; }
        public Nullable<decimal> item_cost3 { get; set; }
        public Nullable<decimal> item_sprice3 { get; set; }
        public Nullable<int> item_ins { get; set; }
        public Nullable<System.DateTime> item_exp_date { get; set; }
        public string item_gcode { get; set; }
        public string item_ins_plan { get; set; }
        public string item_generic_code { get; set; }
        public string item_pac_size { get; set; }
        public string item_dis_mode { get; set; }
        public string item_pprice_public { get; set; }
        public string item_pprice_pha { get; set; }
        public string item_uprice_public { get; set; }
        public string item_uprice_pha { get; set; }
        public string item_agent_name { get; set; }
        public string item_man_name { get; set; }
        public Nullable<int> item_madeby { get; set; }
    }
}
