//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Minors_Assessment_Consent
    {
        public int macId { get; set; }
        public Nullable<int> mac_appId { get; set; }
        public string mac_1 { get; set; }
        public string mac_status { get; set; }
        public Nullable<int> mac_made_by { get; set; }
        public Nullable<System.DateTime> mac_date_created { get; set; }
        public Nullable<int> mac_modified_by { get; set; }
        public Nullable<System.DateTime> mac_date_modified { get; set; }
    }
}
