//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_NAS_DENTAL_NEW
    {
        public int cndnId { get; set; }
        public Nullable<int> cndn_appId { get; set; }
        public string cndn_1 { get; set; }
        public string cndn_2 { get; set; }
        public string cndn_3 { get; set; }
        public string cndn_4 { get; set; }
        public string cndn_5 { get; set; }
        public string cndn_6 { get; set; }
        public string cndn_7 { get; set; }
        public string cndn_chk { get; set; }
        public string cndn_status { get; set; }
        public Nullable<int> cndn_madeby { get; set; }
        public Nullable<int> cndn_modifyby { get; set; }
        public Nullable<System.DateTime> cndn_date_created { get; set; }
        public Nullable<System.DateTime> cndn_date_modified { get; set; }
    }
}
