//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_NASAL_ENDOSCOPY_REPORT
    {
        public int nerId { get; set; }
        public Nullable<int> ner_appId { get; set; }
        public string ner_notes { get; set; }
        public Nullable<int> ner_madeby { get; set; }
        public string ner_status { get; set; }
        public Nullable<System.DateTime> ner_date_created { get; set; }
        public Nullable<System.DateTime> ner_date_modified { get; set; }
    }
}
