//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_NAS_DARAL_TAKAFUL_NEW
    {
        public int ndtnId { get; set; }
        public Nullable<int> ndtn_appId { get; set; }
        public string ndtn_1 { get; set; }
        public string ndtn_2 { get; set; }
        public string ndtn_3 { get; set; }
        public string ndtn_4 { get; set; }
        public string ndtn_5 { get; set; }
        public string ndtn_6 { get; set; }
        public string ndtn_7 { get; set; }
        public string ndtn_8 { get; set; }
        public string ndtn_9 { get; set; }
        public string ndtn_10 { get; set; }
        public string ndtn_11 { get; set; }
        public string ndtn_12 { get; set; }
        public string ndtn_13 { get; set; }
        public string ndtn_14 { get; set; }
        public string ndtn_15 { get; set; }
        public string ndtn_16 { get; set; }
        public string ndtn_17 { get; set; }
        public string ndtn_18 { get; set; }
        public string ndtn_19 { get; set; }
        public string ndtn_20 { get; set; }
        public string ndtn_21 { get; set; }
        public string ndtn_22 { get; set; }
        public string ndtn_23 { get; set; }
        public string ndtn_24 { get; set; }
        public string ndtn_25 { get; set; }
        public string ndtn_26 { get; set; }
        public string ndtn_27 { get; set; }
        public string ndtn_28 { get; set; }
        public string ndtn_29 { get; set; }
        public string ndtn_30 { get; set; }
        public string ndtn_31 { get; set; }
        public string ndtn_32 { get; set; }
        public string ndtn_33 { get; set; }
        public string ndtn_34 { get; set; }
        public string ndtn_35 { get; set; }
        public string ndtn_36 { get; set; }
        public string ndtn_37 { get; set; }
        public string ndtn_38 { get; set; }
        public string ndtn_39 { get; set; }
        public string ndtn_40 { get; set; }
        public string ndtn_41 { get; set; }
        public string ndtn_42 { get; set; }
        public string ndtn_43 { get; set; }
        public string ndtn_checkbox { get; set; }
        public string ndtn_status { get; set; }
        public Nullable<int> ndtn_madeby { get; set; }
        public Nullable<int> ndtn_modifyby { get; set; }
        public Nullable<System.DateTime> ndtn_date_created { get; set; }
        public Nullable<System.DateTime> ndtn_date_modified { get; set; }
    }
}
