//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_NAS_PRESCRIPTION_NEW
    {
        public int cnrnId { get; set; }
        public Nullable<int> cnrn_appId { get; set; }
        public string cnrn_1 { get; set; }
        public string cnrn_2 { get; set; }
        public string cnrn_3 { get; set; }
        public string cnrn_4 { get; set; }
        public string cnrn_5 { get; set; }
        public string cnrn_6 { get; set; }
        public string cnrn_chk { get; set; }
        public string cnrn_status { get; set; }
        public Nullable<int> cnrn_madeby { get; set; }
        public Nullable<int> cnrn_modifyby { get; set; }
        public Nullable<System.DateTime> cnrn_date_created { get; set; }
        public Nullable<System.DateTime> cnrn_date_modified { get; set; }
    }
}
