//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_NEXTCARE_ASNIC_NEW
    {
        public int cnanId { get; set; }
        public Nullable<int> cnan_appId { get; set; }
        public string cnan_1 { get; set; }
        public string cnan_2 { get; set; }
        public string cnan_3 { get; set; }
        public string cnan_4 { get; set; }
        public string cnan_5 { get; set; }
        public string cnan_6 { get; set; }
        public string cnan_7 { get; set; }
        public string cnan_8 { get; set; }
        public string cnan_9 { get; set; }
        public string cnan_10 { get; set; }
        public string cnan_11 { get; set; }
        public string cnan_12 { get; set; }
        public string cnan_13 { get; set; }
        public string cnan_14 { get; set; }
        public string cnan_15 { get; set; }
        public string cnan_16 { get; set; }
        public string cnan_17 { get; set; }
        public string cnan_18 { get; set; }
        public string cnan_19 { get; set; }
        public string cnan_20 { get; set; }
        public string cnan_21 { get; set; }
        public string cnan_22 { get; set; }
        public string cnan_23 { get; set; }
        public string cnan_24 { get; set; }
        public string cnan_25 { get; set; }
        public string cnan_26 { get; set; }
        public string cnan_27 { get; set; }
        public string cnan_28 { get; set; }
        public string cnan_29 { get; set; }
        public string cnan_30 { get; set; }
        public string cnan_31 { get; set; }
        public string cnan_32 { get; set; }
        public string cnan_33 { get; set; }
        public string cnan_34 { get; set; }
        public string cnan_35 { get; set; }
        public string cnan_36 { get; set; }
        public string cnan_37 { get; set; }
        public string cnan_38 { get; set; }
        public string cnan_39 { get; set; }
        public string cnan_40 { get; set; }
        public string cnan_41 { get; set; }
        public string cnan_checkbox { get; set; }
        public Nullable<System.DateTime> cnan_date1 { get; set; }
        public Nullable<System.DateTime> cnan_date2 { get; set; }
        public Nullable<System.DateTime> cnan_date3 { get; set; }
        public string cnan_status { get; set; }
        public Nullable<int> cnan_madeby { get; set; }
        public Nullable<int> cnan_modifyby { get; set; }
        public Nullable<System.DateTime> cnan_date_created { get; set; }
        public Nullable<System.DateTime> cnan_date_modified { get; set; }
    }
}
