//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_NEXTCARE_ORIENT_NEW
    {
        public int cnonId { get; set; }
        public Nullable<int> cnon_appId { get; set; }
        public string cnon_1 { get; set; }
        public string cnon_2 { get; set; }
        public string cnon_3 { get; set; }
        public string cnon_4 { get; set; }
        public string cnon_5 { get; set; }
        public string cnon_6 { get; set; }
        public string cnon_7 { get; set; }
        public string cnon_8 { get; set; }
        public string cnon_9 { get; set; }
        public string cnon_10 { get; set; }
        public string cnon_11 { get; set; }
        public string cnon_12 { get; set; }
        public string cnon_13 { get; set; }
        public string cnon_14 { get; set; }
        public string cnon_15 { get; set; }
        public string cnon_16 { get; set; }
        public string cnon_17 { get; set; }
        public string cnon_18 { get; set; }
        public string cnon_19 { get; set; }
        public string cnon_20 { get; set; }
        public string cnon_21 { get; set; }
        public string cnon_22 { get; set; }
        public string cnon_23 { get; set; }
        public string cnon_24 { get; set; }
        public string cnon_25 { get; set; }
        public string cnon_26 { get; set; }
        public string cnon_27 { get; set; }
        public string cnon_28 { get; set; }
        public string cnon_29 { get; set; }
        public string cnon_30 { get; set; }
        public string cnon_31 { get; set; }
        public string cnon_32 { get; set; }
        public string cnon_33 { get; set; }
        public string cnon_34 { get; set; }
        public string cnon_35 { get; set; }
        public string cnon_36 { get; set; }
        public string cnon_37 { get; set; }
        public string cnon_38 { get; set; }
        public string cnon_39 { get; set; }
        public string cnon_40 { get; set; }
        public string cnon_41 { get; set; }
        public string cnon_checkbox { get; set; }
        public Nullable<System.DateTime> cnon_date1 { get; set; }
        public Nullable<System.DateTime> cnon_date2 { get; set; }
        public Nullable<System.DateTime> cnon_date3 { get; set; }
        public string cnon_status { get; set; }
        public Nullable<int> cnon_madeby { get; set; }
        public Nullable<int> cnon_modifyby { get; set; }
        public Nullable<System.DateTime> cnon_date_created { get; set; }
        public Nullable<System.DateTime> cnon_date_modified { get; set; }
    }
}
