//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_NOTES_MASTER
    {
        public int nsmId { get; set; }
        public string nsm_title { get; set; }
        public string nsm_desc { get; set; }
        public Nullable<int> nsm_madeby { get; set; }
        public string nsm_status { get; set; }
        public string nsm_flag { get; set; }
        public Nullable<System.DateTime> nsm_date_created { get; set; }
        public Nullable<System.DateTime> nsm_date_modified { get; set; }
    }
}
