//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_NURSE_NOTES
    {
        public int nurseId { get; set; }
        public int nurse_appId { get; set; }
        public string nurse_notes { get; set; }
        public string nurse_status { get; set; }
        public Nullable<int> nurse_madeby { get; set; }
        public Nullable<System.DateTime> nurse_date_created { get; set; }
        public Nullable<System.DateTime> nurse_date_modified { get; set; }
    }
}
