//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_OMAN_DENTAL_NEW
    {
        public int codnId { get; set; }
        public Nullable<int> codn_appId { get; set; }
        public string codn_1 { get; set; }
        public string codn_2 { get; set; }
        public string codn_3 { get; set; }
        public string codn_4 { get; set; }
        public string codn_5 { get; set; }
        public string codn_6 { get; set; }
        public string codn_7 { get; set; }
        public string codn_8 { get; set; }
        public string codn_9 { get; set; }
        public string codn_10 { get; set; }
        public string codn_11 { get; set; }
        public string codn_12 { get; set; }
        public string codn_13 { get; set; }
        public string codn_14 { get; set; }
        public string codn_15 { get; set; }
        public string codn_16 { get; set; }
        public string codn_17 { get; set; }
        public string codn_18 { get; set; }
        public string codn_19 { get; set; }
        public string codn_20 { get; set; }
        public string codn_21 { get; set; }
        public string codn_22 { get; set; }
        public string codn_23 { get; set; }
        public string codn_24 { get; set; }
        public string codn_25 { get; set; }
        public string codn_26 { get; set; }
        public string codn_27 { get; set; }
        public string codn_28 { get; set; }
        public string codn_29 { get; set; }
        public string codn_30 { get; set; }
        public string codn_31 { get; set; }
        public string codn_32 { get; set; }
        public string codn_33 { get; set; }
        public string codn_34 { get; set; }
        public string codn_35 { get; set; }
        public string codn_36 { get; set; }
        public string codn_37 { get; set; }
        public string codn_38 { get; set; }
        public string codn_39 { get; set; }
        public string codn_40 { get; set; }
        public string codn_41 { get; set; }
        public string codn_42 { get; set; }
        public string codn_43 { get; set; }
        public string codn_44 { get; set; }
        public string codn_45 { get; set; }
        public string codn_46 { get; set; }
        public string codn_47 { get; set; }
        public string codn_48 { get; set; }
        public string codn_49 { get; set; }
        public string codn_50 { get; set; }
        public string codn_51 { get; set; }
        public string codn_52 { get; set; }
        public string codn_53 { get; set; }
        public string codn_54 { get; set; }
        public string codn_55 { get; set; }
        public string codn_56 { get; set; }
        public string codn_57 { get; set; }
        public string codn_58 { get; set; }
        public string codn_59 { get; set; }
        public string codn_60 { get; set; }
        public string codn_61 { get; set; }
        public string codn_62 { get; set; }
        public string codn_63 { get; set; }
        public string codn_64 { get; set; }
        public string codn_65 { get; set; }
        public string codn_66 { get; set; }
        public string codn_67 { get; set; }
        public string codn_checkbox { get; set; }
        public Nullable<System.DateTime> codn_date1 { get; set; }
        public string codn_status { get; set; }
        public Nullable<int> codn_madeby { get; set; }
        public Nullable<int> codn_modifyby { get; set; }
        public Nullable<System.DateTime> codn_date_created { get; set; }
        public Nullable<System.DateTime> codn_date_modified { get; set; }
    }
}
