//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ORIENT_REMB_NEW
    {
        public int orntId { get; set; }
        public Nullable<int> ornt_appId { get; set; }
        public string ornt_1 { get; set; }
        public string ornt_2 { get; set; }
        public string ornt_3 { get; set; }
        public string ornt_4 { get; set; }
        public string ornt_5 { get; set; }
        public string ornt_6 { get; set; }
        public string ornt_7 { get; set; }
        public string ornt_status { get; set; }
        public string ornt_chk { get; set; }
        public Nullable<System.DateTime> ornt_date1 { get; set; }
        public Nullable<System.DateTime> ornt_date2 { get; set; }
        public Nullable<System.DateTime> ornt_date3 { get; set; }
        public Nullable<int> ornt_madeby { get; set; }
        public Nullable<int> ornt_modifyby { get; set; }
        public Nullable<System.DateTime> ornt_date_created { get; set; }
        public Nullable<System.DateTime> ornt_date_modified { get; set; }
    }
}
