//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PATIENT_FEEDBACK_FORM
    {
        public int pffId { get; set; }
        public string pff_name { get; set; }
        public string pff_mob { get; set; }
        public string pff_1 { get; set; }
        public string pff_2 { get; set; }
        public string pff_3 { get; set; }
        public string pff_4 { get; set; }
        public string pff_5 { get; set; }
        public string pff_6 { get; set; }
        public Nullable<System.DateTime> pff_date_created { get; set; }
        public Nullable<System.DateTime> pff_date_modified { get; set; }
    }
}
