//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Patient_Dental_Implant_Consent_Arabic
    {
        public int dicaId { get; set; }
        public Nullable<int> dica_appId { get; set; }
        public string dica_1 { get; set; }
        public string dica_2 { get; set; }
        public string dica_3 { get; set; }
        public string dica_status { get; set; }
        public Nullable<int> dica_made_by { get; set; }
        public Nullable<int> dica_modified_by { get; set; }
        public Nullable<System.DateTime> dica_date_created { get; set; }
        public Nullable<System.DateTime> dica_date_modified { get; set; }
    }
}
