//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PACKAGE_SERVICES
    {
        public int psId { get; set; }
        public Nullable<int> ps_services { get; set; }
        public Nullable<int> ps_package { get; set; }
        public string ps_status { get; set; }
        public Nullable<int> ps_madeby { get; set; }
        public Nullable<System.DateTime> ps_date_created { get; set; }
        public Nullable<System.DateTime> ps_date_modified { get; set; }
        public Nullable<double> ps_qty { get; set; }
        public Nullable<double> ps_oriPrice { get; set; }
        public Nullable<double> ps_disPrice { get; set; }
    }
}
