//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Package_Order
    {
        public int poId { get; set; }
        public string po_refno { get; set; }
        public Nullable<System.DateTime> po_date { get; set; }
        public Nullable<int> po_patient { get; set; }
        public Nullable<int> po_branch { get; set; }
        public Nullable<int> po_package { get; set; }
        public string po_status { get; set; }
        public Nullable<int> po_madeby { get; set; }
        public string po_notes { get; set; }
        public Nullable<System.DateTime> po_exp_date { get; set; }
        public Nullable<System.DateTime> po_date_created { get; set; }
        public Nullable<System.DateTime> po_date_modified { get; set; }
        public string po_services { get; set; }
    }
}
