//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PageAccess
    {
        public int PAId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> L3Id { get; set; }
        public Nullable<bool> isCreate { get; set; }
        public Nullable<bool> isUpdate { get; set; }
        public Nullable<bool> isRead { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<bool> isExport { get; set; }
        public Nullable<bool> isPrint { get; set; }
    }
}
