//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Package_Master
    {
        public int pkgId { get; set; }
        public string pkg_code { get; set; }
        public string pkg_name { get; set; }
        public Nullable<decimal> pkg_price { get; set; }
        public string pkg_status { get; set; }
        public Nullable<int> pkg_madeby { get; set; }
        public Nullable<System.DateTime> pkg_date_created { get; set; }
        public Nullable<System.DateTime> pkg_date_modified { get; set; }
    }
}
