//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PATIENT_DIAGNOSIS_FAVOURITES
    {
        public int pdfId { get; set; }
        public int pdf_empId { get; set; }
        public int pdf_diagnosis { get; set; }
        public string pdf_notes { get; set; }
    }
}
