//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PATIENT_DIAGNOSIS
    {
        public int padId { get; set; }
        public int pad_appId { get; set; }
        public int pad_diagnosis { get; set; }
        public string pad_notes { get; set; }
        public string pad_type { get; set; }
        public string pad_gender { get; set; }
        public Nullable<int> pad_age { get; set; }
        public Nullable<int> pad_nat { get; set; }
        public Nullable<System.DateTime> pad_app_fdate { get; set; }
        public Nullable<int> pad_branch { get; set; }
        public string pad_status { get; set; }
        public Nullable<System.DateTime> pad_date_created { get; set; }
        public Nullable<System.DateTime> pad_date_modified { get; set; }
        public Nullable<int> pad_madeby { get; set; }
        public Nullable<int> pad_modifiedby { get; set; }
        public string pad_madeby_name { get; set; }
        public string pad_modifiedby_name { get; set; }
        public string pad_role_code { get; set; }
        public string pad_role_type { get; set; }
        public Nullable<int> pad_year { get; set; }
    }
}
