//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PATIENTS
    {
        public int patId { get; set; }
        public Nullable<int> pat_code { get; set; }
        public string pat_name { get; set; }
        public Nullable<System.DateTime> pat_dob { get; set; }
        public string pat_gender { get; set; }
        public string pat_ms { get; set; }
        public Nullable<int> pat_nat { get; set; }
        public string pat_tel { get; set; }
        public string pat_mob { get; set; }
        public string pat_fax { get; set; }
        public string pat_email { get; set; }
        public string pat_pobox { get; set; }
        public string pat_address { get; set; }
        public string pat_city { get; set; }
        public Nullable<int> pat_country { get; set; }
        public string pat_photo { get; set; }
        public string pat_notes { get; set; }
        public string pat_account { get; set; }
        public string pat_status { get; set; }
        public Nullable<System.DateTime> pat_date_created { get; set; }
        public Nullable<System.DateTime> pat_date_modified { get; set; }
        public string pat_hear { get; set; }
        public string pat_lang { get; set; }
        public Nullable<int> pat_credit { get; set; }
        public string pat_emirateid { get; set; }
        public string pat_doc_1 { get; set; }
        public string pat_doc_2 { get; set; }
        public string pat_doc_3 { get; set; }
        public string pat_doc_4 { get; set; }
        public string pat_doc_5 { get; set; }
        public Nullable<System.DateTime> pat_last_visited { get; set; }
        public Nullable<int> pat_referal { get; set; }
        public string pat_mname { get; set; }
        public string pat_lname { get; set; }
        public string pat_ec_name1 { get; set; }
        public string pat_ec_rel1 { get; set; }
        public string pat_ec_tel1 { get; set; }
        public string pat_ec_tel11 { get; set; }
        public string pat_ec_name2 { get; set; }
        public string pat_ec_rel2 { get; set; }
        public string pat_ec_tel2 { get; set; }
        public string pat_ec_tel22 { get; set; }
        public string pat_ec_name3 { get; set; }
        public string pat_ec_rel3 { get; set; }
        public string pat_ec_tel3 { get; set; }
        public string pat_ec_tel33 { get; set; }
        public Nullable<int> pat_branch { get; set; }
        public string pat_class { get; set; }
        public Nullable<decimal> pat_obal { get; set; }
        public string pat_obal_type { get; set; }
        public Nullable<int> pat_madeby { get; set; }
        public string pat_religion { get; set; }
        public string pat_citizen { get; set; }
        public string pat_email_type { get; set; }
        public string pat_mob_type { get; set; }
        public string pat_race { get; set; }
        public string pat_address_type { get; set; }
        public string pat_consent_flag { get; set; }
        public string pat_ethnic { get; set; }
        public string pat_contact_role { get; set; }
        public string pat_title { get; set; }
        public string pat_rel_name { get; set; }
        public string pat_rel_type { get; set; }
        public string pat_rel_address { get; set; }
        public string pat_rel_address_type { get; set; }
        public string pat_rel_mob { get; set; }
        public string pat_rel_mob_type { get; set; }
        public string pat_rel_country { get; set; }
        public Nullable<int> pat_slno { get; set; }
        public string pat_passport { get; set; }
        public string pat_name_arabic { get; set; }
        public string pat_lname_arabic { get; set; }
        public string pat_occupation { get; set; }
    }
}
