//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Patient_Feedback
    {
        public int cpfId { get; set; }
        public Nullable<int> cpf_appId { get; set; }
        public string cpf_text { get; set; }
        public string cpf_rating { get; set; }
        public string cpf_status { get; set; }
        public Nullable<System.DateTime> cpf_date_created { get; set; }
        public Nullable<System.DateTime> cpf_date_modified { get; set; }
    }
}
