//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PATIENT_VACCINATIONS
    {
        public int pvId { get; set; }
        public Nullable<int> pv_appId { get; set; }
        public Nullable<int> pv_vaccination { get; set; }
        public string pv_notes { get; set; }
        public Nullable<System.DateTime> pv_date_created { get; set; }
        public Nullable<System.DateTime> pv_date_modified { get; set; }
        public string pv_batchno { get; set; }
        public string pv_manufacturer { get; set; }
        public string pv_status { get; set; }
        public Nullable<int> pv_madeby { get; set; }
        public Nullable<int> pv_modifyby { get; set; }
        public Nullable<System.DateTime> pv_exp_date { get; set; }
        public string pv_dose { get; set; }
        public string pv_reminder_notes { get; set; }
        public Nullable<System.DateTime> pv_date { get; set; }
    }
}
