//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Patient_Package_Servies
    {
        public int ppsId { get; set; }
        public Nullable<int> pps_poId { get; set; }
        public Nullable<int> pps_posId { get; set; }
        public Nullable<int> pps_services { get; set; }
        public Nullable<int> pps_patId { get; set; }
        public Nullable<int> pps_appId { get; set; }
        public Nullable<int> pps_invId { get; set; }
        public Nullable<int> pps_ptId { get; set; }
        public Nullable<int> pps_qty { get; set; }
        public Nullable<int> pps_used { get; set; }
        public Nullable<int> pps_balance { get; set; }
        public Nullable<decimal> pps_price { get; set; }
        public Nullable<int> pps_package { get; set; }
        public string pps_status { get; set; }
        public Nullable<int> pps_madeby { get; set; }
        public Nullable<System.DateTime> pps_date_created { get; set; }
    }
}
