//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PATIENT_DENT_HISTORY
    {
        public int pdId { get; set; }
        public Nullable<int> pd_appId { get; set; }
        public string pd_medicaltreat { get; set; }
        public string pd_hospitalized { get; set; }
        public string pd_medications { get; set; }
        public string pd_medicationsyes { get; set; }
        public string pd_tobacco { get; set; }
        public string pd_gums { get; set; }
        public string pd_hotcold { get; set; }
        public string pd_sweetsour { get; set; }
        public string pd_teethpain { get; set; }
        public string pd_soresjumps { get; set; }
        public string pd_headinjuries { get; set; }
        public string pd_clicking { get; set; }
        public string pd_pain { get; set; }
        public string pd_openingclosing { get; set; }
        public string pd_chewing { get; set; }
        public string pd_clench { get; set; }
        public string pd_bitelips { get; set; }
        public string pd_difficultextract { get; set; }
        public string pd_prolonged { get; set; }
        public string pd_gems { get; set; }
        public string pd_filling { get; set; }
        public string pd_w_medicaltreat { get; set; }
        public string pd_w_hospitalized { get; set; }
        public string pd_w_medications { get; set; }
        public string pd_w_amenorrhoea { get; set; }
        public string pd_last_dental_exam { get; set; }
        public Nullable<System.DateTime> pd_date_created { get; set; }
        public Nullable<System.DateTime> pd_date_modified { get; set; }
        public Nullable<int> pd_madeby { get; set; }
        public string pd_status { get; set; }
    }
}
