//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PATIENT_PACKAGES
    {
        public int cppId { get; set; }
        public Nullable<int> cpp_appId { get; set; }
        public Nullable<int> cpp_ptId { get; set; }
        public Nullable<int> cpp_patId { get; set; }
        public Nullable<System.DateTime> cpp_pur_date { get; set; }
        public Nullable<System.DateTime> cpp_exp_date { get; set; }
        public string cpp_tr_code { get; set; }
        public string cpp_tr_name { get; set; }
        public Nullable<int> cpp_ses { get; set; }
        public Nullable<int> cpp_used { get; set; }
        public Nullable<int> cpp_bal { get; set; }
        public string cpp_exp_reason { get; set; }
        public string cpp_status { get; set; }
        public Nullable<int> cpp_madeby { get; set; }
        public Nullable<System.DateTime> cpp_date_created { get; set; }
        public Nullable<System.DateTime> cpp_date_modified { get; set; }
    }
}
