//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PAST_FAMILY_HISTORY
    {
        public int pfId { get; set; }
        public Nullable<int> pf_appId { get; set; }
        public string pf_past { get; set; }
        public string pf_family { get; set; }
        public string pf_other { get; set; }
        public string pf_smok { get; set; }
        public string pf_smok_details { get; set; }
        public string pf_alco { get; set; }
        public string pf_alco_details { get; set; }
        public string pf_drug { get; set; }
        public string pf_drug_details { get; set; }
        public string pf_status { get; set; }
        public Nullable<int> pf_madeby { get; set; }
        public Nullable<int> pf_modifyby { get; set; }
        public Nullable<System.DateTime> pf_date_created { get; set; }
        public Nullable<System.DateTime> pf_date_modified { get; set; }
        public string pf_surgical { get; set; }
        public string pf_smok_habit { get; set; }
        public string pf_alco_habit { get; set; }
        public string pf_drug_habit { get; set; }
    }
}
