//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PATIENT_ORAL_EXAM
    {
        public int oeId { get; set; }
        public Nullable<int> oe_appId { get; set; }
        public string oe_present_ill { get; set; }
        public string oe_pain { get; set; }
        public string oe_duration { get; set; }
        public string oe_infecious { get; set; }
        public string oe_infecious_other { get; set; }
        public string oe_systemic { get; set; }
        public string oe_systemic_other { get; set; }
        public string oe_past_med { get; set; }
        public string oe_past_med_other { get; set; }
        public string oe_fall_risk { get; set; }
        public string oe_fall_risk_other { get; set; }
        public string oe_fall_risk_type { get; set; }
        public string oe_notes { get; set; }
        public string oe_extra_oral { get; set; }
        public string oe_intra_oral { get; set; }
        public string oe_oral_notes { get; set; }
        public Nullable<System.DateTime> oe_date_created { get; set; }
        public Nullable<System.DateTime> oe_date_modified { get; set; }
        public Nullable<int> oe_madeby { get; set; }
        public string oe_status { get; set; }
    }
}
