//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PATIENT_VACCINATIONS2
    {
        public int vacId { get; set; }
        public Nullable<int> vac_appId { get; set; }
        public string vac_name { get; set; }
        public Nullable<System.DateTime> vac_date1 { get; set; }
        public Nullable<System.DateTime> vac_date2 { get; set; }
        public Nullable<System.DateTime> vac_date3 { get; set; }
        public Nullable<System.DateTime> vac_date4 { get; set; }
        public Nullable<System.DateTime> vac_date5 { get; set; }
        public string vac_status { get; set; }
        public Nullable<int> vac_madeby { get; set; }
        public Nullable<int> vac_modifyby { get; set; }
        public Nullable<System.DateTime> vac_date_created { get; set; }
        public Nullable<System.DateTime> vac_date_modified { get; set; }
    }
}
