//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PATIENT_TREATMENTS_CREDIT_NOTE
    {
        public int ptcId { get; set; }
        public int ptc_appId { get; set; }
        public string ptc_type { get; set; }
        public int ptc_treatment { get; set; }
        public Nullable<int> ptc_qty { get; set; }
        public string ptc_notes { get; set; }
        public string ptc_teeth { get; set; }
        public string ptc_sur { get; set; }
        public Nullable<int> ptc_ses { get; set; }
        public Nullable<int> ptc_treat_type { get; set; }
        public Nullable<decimal> ptc_share { get; set; }
        public Nullable<decimal> ptc_uprice { get; set; }
        public Nullable<decimal> ptc_total { get; set; }
        public Nullable<decimal> ptc_disc { get; set; }
        public Nullable<decimal> ptc_ded { get; set; }
        public Nullable<decimal> ptc_copay { get; set; }
        public Nullable<decimal> ptc_dcopay { get; set; }
        public Nullable<decimal> ptc_net { get; set; }
        public string ptc_invno { get; set; }
        public Nullable<int> ptc_insurance { get; set; }
        public Nullable<decimal> ptc_dded { get; set; }
        public Nullable<decimal> ptc_lded { get; set; }
        public Nullable<decimal> ptc_rded { get; set; }
        public Nullable<decimal> ptc_mded { get; set; }
        public Nullable<double> ptc_pdisc { get; set; }
        public Nullable<decimal> ptc_vat { get; set; }
        public string ptc_vat_type { get; set; }
        public Nullable<decimal> ptc_vat2 { get; set; }
        public string ptc_status { get; set; }
        public Nullable<System.DateTime> ptc_date_invoiced { get; set; }
        public Nullable<System.DateTime> ptc_date_created { get; set; }
        public Nullable<System.DateTime> ptc_date_modified { get; set; }
    }
}
