//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PerioChart_Old
    {
        public int pcoId { get; set; }
        public Nullable<int> pco_appId { get; set; }
        public string pco_progChartCSV { get; set; }
        public string pco_vitaChartCSV { get; set; }
        public string pco_bleedChartCSV { get; set; }
        public string pco_furcChartCSV { get; set; }
        public string pco_mobiChartCSV { get; set; }
        public string pco_fremiChartCSV { get; set; }
        public string pco_attachChartCSV { get; set; }
        public string pco_receChartCSV { get; set; }
        public string pco_probChartCSV { get; set; }
        public string pco_buttonChartCSV { get; set; }
        public string pco_plaq_chart { get; set; }
        public string pco_status { get; set; }
        public Nullable<int> pco_madeby { get; set; }
        public Nullable<System.DateTime> pco_date_created { get; set; }
        public Nullable<int> pco_modified_by { get; set; }
        public Nullable<System.DateTime> pco_date_modified { get; set; }
    }
}
