//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PHYSICAIN_QUERY
    {
        public int pqId { get; set; }
        public Nullable<int> pq_appId { get; set; }
        public string pq_txt1 { get; set; }
        public string pq_txt2 { get; set; }
        public string pq_txt3 { get; set; }
        public string pq_txt4 { get; set; }
        public string pq_txt5 { get; set; }
        public string pq_status { get; set; }
        public Nullable<int> pq_madeby { get; set; }
        public Nullable<int> pq_modifyby { get; set; }
        public Nullable<System.DateTime> pq_date_created { get; set; }
        public Nullable<System.DateTime> pq_date_modified { get; set; }
    }
}
