//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PHYSICAIN_NURSE_QUERY
    {
        public int pnqId { get; set; }
        public Nullable<int> pnq_appId { get; set; }
        public string pnq_query { get; set; }
        public string pnq_response { get; set; }
        public Nullable<int> pnq_fromemp { get; set; }
        public Nullable<int> pnq_toemp { get; set; }
        public string pnq_status { get; set; }
        public Nullable<int> pnq_madeby { get; set; }
        public Nullable<System.DateTime> pnq_date_created { get; set; }
        public Nullable<System.DateTime> pnq_date_modified { get; set; }
    }
}
