//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PHYSICAL_EXAMINATION
    {
        public int peId { get; set; }
        public Nullable<int> pe_appId { get; set; }
        public string pe_1 { get; set; }
        public string pe_2 { get; set; }
        public string pe_3 { get; set; }
        public string pe_4 { get; set; }
        public string pe_5 { get; set; }
        public string pe_6 { get; set; }
        public string pe_7 { get; set; }
        public string pe_8 { get; set; }
        public string pe_9 { get; set; }
        public string pe_10 { get; set; }
        public string pe_11 { get; set; }
        public string pe_12 { get; set; }
        public string pe_13 { get; set; }
        public string pe_14 { get; set; }
        public string pe_15 { get; set; }
        public string pe_16 { get; set; }
        public string pe_17 { get; set; }
        public string pe_18 { get; set; }
        public string pe_19 { get; set; }
        public string pe_20 { get; set; }
        public string pe_21 { get; set; }
        public string pe_22 { get; set; }
        public string pe_23 { get; set; }
        public string pe_24 { get; set; }
        public string pe_25 { get; set; }
        public string pe_26 { get; set; }
        public string pe_27 { get; set; }
        public string pe_28 { get; set; }
        public string pe_29 { get; set; }
        public string pe_30 { get; set; }
        public string pe_31 { get; set; }
        public string pe_32 { get; set; }
        public string pe_33 { get; set; }
        public string pe_34 { get; set; }
        public string pe_35 { get; set; }
        public string pe_36 { get; set; }
        public string pe_37 { get; set; }
        public string pe_38 { get; set; }
        public string pe_39 { get; set; }
        public string pe_40 { get; set; }
        public string pe_41 { get; set; }
        public string pe_42 { get; set; }
        public string pe_43 { get; set; }
        public string pe_44 { get; set; }
        public string pe_45 { get; set; }
        public string pe_46 { get; set; }
        public string pe_47 { get; set; }
        public string pe_48 { get; set; }
        public string pe_49 { get; set; }
        public string pe_50 { get; set; }
        public string pe_51 { get; set; }
        public string pe_52 { get; set; }
        public string pe_53 { get; set; }
        public string pe_54 { get; set; }
        public string pe_55 { get; set; }
        public string pe_56 { get; set; }
        public string pe_57 { get; set; }
        public string pe_58 { get; set; }
        public string pe_59 { get; set; }
        public string pe_60 { get; set; }
        public string pe_61 { get; set; }
        public string pe_62 { get; set; }
        public string pe_63 { get; set; }
        public string pe_64 { get; set; }
        public string pe_65 { get; set; }
        public string pe_66 { get; set; }
        public string pe_67 { get; set; }
        public string pe_68 { get; set; }
        public string pe_69 { get; set; }
        public string pe_70 { get; set; }
        public string pe_71 { get; set; }
        public Nullable<System.DateTime> pe_date_created { get; set; }
        public Nullable<System.DateTime> pe_date_modified { get; set; }
        public string pe_status { get; set; }
        public Nullable<int> pe_madeby { get; set; }
        public Nullable<int> pe_modifyby { get; set; }
        public string pe_notes { get; set; }
        public string pe_72 { get; set; }
    }
}
