//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Prefixes
    {
        public int pfxId { get; set; }
        public string pfx_prefix { get; set; }
        public string pfx_type { get; set; }
        public string pfx_slno { get; set; }
        public Nullable<int> pfx_branch { get; set; }
        public string pfx_change { get; set; }
        public string pfx_changeby { get; set; }
        public string pfx_status { get; set; }
        public Nullable<int> pfx_madeby { get; set; }
        public Nullable<System.DateTime> pfx_date_created { get; set; }
        public Nullable<System.DateTime> pfx_date_modified { get; set; }
    }
}
