//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Pregnancy_Testing_Form
    {
        public int ptfId { get; set; }
        public Nullable<int> ptf_appId { get; set; }
        public string ptf_1 { get; set; }
        public string ptf_2 { get; set; }
        public string ptf_3 { get; set; }
        public string ptf_4 { get; set; }
        public string ptf_5 { get; set; }
        public string ptf_6 { get; set; }
        public string ptf_7 { get; set; }
        public string ptf_8 { get; set; }
        public string ptf_9 { get; set; }
        public string ptf_10 { get; set; }
        public string ptf_11 { get; set; }
        public string ptf_12 { get; set; }
        public string ptf_13 { get; set; }
        public string ptf_14 { get; set; }
        public string ptf_15 { get; set; }
        public string ptf_16 { get; set; }
        public string ptf_17 { get; set; }
        public string ptf_18 { get; set; }
        public string ptf_19 { get; set; }
        public string ptf_20 { get; set; }
        public string ptf_21 { get; set; }
        public string ptf_22 { get; set; }
        public string ptf_23 { get; set; }
        public string ptf_24 { get; set; }
        public string ptf_25 { get; set; }
        public string ptf_26 { get; set; }
        public string ptf_27 { get; set; }
        public string ptf_28 { get; set; }
        public string ptf_29 { get; set; }
        public string ptf_30 { get; set; }
        public string ptf_31 { get; set; }
        public string ptf_32 { get; set; }
        public string ptf_33 { get; set; }
        public string ptf_34 { get; set; }
        public string ptf_35 { get; set; }
        public string ptf_36 { get; set; }
        public string ptf_37 { get; set; }
        public string ptf_38 { get; set; }
        public string ptf_39 { get; set; }
        public string ptf_40 { get; set; }
        public string ptf_41 { get; set; }
        public string ptf_42 { get; set; }
        public string ptf_43 { get; set; }
        public string ptf_44 { get; set; }
        public string ptf_45 { get; set; }
        public string ptf_46 { get; set; }
        public string ptf_47 { get; set; }
        public string ptf_48 { get; set; }
        public string ptf_49 { get; set; }
        public string ptf_50 { get; set; }
        public string ptf_51 { get; set; }
        public string ptf_52 { get; set; }
        public string ptf_radio1 { get; set; }
        public string ptf_radio2 { get; set; }
        public string ptf_radio3 { get; set; }
        public string ptf_radio4 { get; set; }
        public string ptf_radio5 { get; set; }
        public string ptf_radio6 { get; set; }
        public Nullable<System.DateTime> ptf_date1 { get; set; }
        public Nullable<System.DateTime> ptf_date2 { get; set; }
        public string ptf_status { get; set; }
        public Nullable<int> ptf_made_by { get; set; }
        public Nullable<System.DateTime> ptf_date_created { get; set; }
        public Nullable<int> ptf_modified_by { get; set; }
        public Nullable<System.DateTime> ptf_date_modified { get; set; }
    }
}
