//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PROFESSION
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Profession { get; set; }
        public string SkilLevel { get; set; }
        public string Status { get; set; }
    }
}
