//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Prior_Requests_Activity_Details
    {
        public int actId { get; set; }
        public Nullable<int> act_appId { get; set; }
        public Nullable<int> act_ptId { get; set; }
        public string act_no { get; set; }
        public Nullable<int> act_slno { get; set; }
        public string act_tr_code { get; set; }
        public Nullable<decimal> act_pt_share { get; set; }
        public Nullable<decimal> act_pt_net { get; set; }
        public string act_pt_deni_code { get; set; }
        public Nullable<decimal> act_pxd_Apay { get; set; }
        public string act_type { get; set; }
        public string act_pt_resub_type { get; set; }
        public Nullable<int> act_pt_qty { get; set; }
        public Nullable<int> act_madeby { get; set; }
        public Nullable<System.DateTime> act_date_submitted { get; set; }
        public Nullable<System.DateTime> act_date_created { get; set; }
        public Nullable<System.DateTime> act_date_modified { get; set; }
        public string act_status { get; set; }
        public string act_xml_type { get; set; }
    }
}
