//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PRESC_FAVOURITES
    {
        public int prefId { get; set; }
        public int pref_empId { get; set; }
        public int pref_medicine { get; set; }
        public string pref_instr { get; set; }
        public string pref_type { get; set; }
        public Nullable<double> pref_qty { get; set; }
        public string pref_qtype { get; set; }
        public string pref_duration { get; set; }
        public string pref_temp1 { get; set; }
        public string pref_temp2 { get; set; }
        public string pref_temp3 { get; set; }
        public string pref_temp4 { get; set; }
        public string pref_temp5 { get; set; }
        public string pref_temp6 { get; set; }
        public string pref_oc_code { get; set; }
        public string pref_oc_type { get; set; }
        public string pref_ra_code { get; set; }
        public string pref_ra_type { get; set; }
    }
}
