//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PRESCRIPTION_TYPE
    {
        public int prtId { get; set; }
        public string prt_code { get; set; }
        public string prt_category { get; set; }
        public string prt_name { get; set; }
    }
}
