//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PRESCRIPTIONS
    {
        public int preId { get; set; }
        public int pre_appId { get; set; }
        public int pre_medicine { get; set; }
        public string pre_instr { get; set; }
        public string pre_type { get; set; }
        public Nullable<double> pre_qty { get; set; }
        public string pre_qtype { get; set; }
        public string pre_duration { get; set; }
        public string pre_temp1 { get; set; }
        public string pre_temp2 { get; set; }
        public string pre_temp3 { get; set; }
        public string pre_temp4 { get; set; }
        public string pre_temp5 { get; set; }
        public string pre_temp6 { get; set; }
        public string pre_eRxRefNo { get; set; }
        public string pre_status { get; set; }
        public Nullable<int> pre_madeby { get; set; }
        public Nullable<int> pre_modifiedby { get; set; }
        public Nullable<System.DateTime> pre_date_created { get; set; }
        public Nullable<System.DateTime> pre_date_modified { get; set; }
        public string pre_oc_code { get; set; }
        public string pre_oc_type { get; set; }
        public string pre_ra_code { get; set; }
        public string pre_ra_type { get; set; }
        public string pre_med_type { get; set; }
    }
}
