//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Prp_Consent_Form
    {
        public int pcfId { get; set; }
        public Nullable<int> pcf_appId { get; set; }
        public string pcf_witness { get; set; }
        public string pcf_status { get; set; }
        public Nullable<int> pcf_made_by { get; set; }
        public Nullable<System.DateTime> pcf_date_created { get; set; }
        public Nullable<int> pcf_modified_by { get; set; }
        public Nullable<System.DateTime> pcf_date_modified { get; set; }
    }
}
