//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_QIC_NAS_REMB_NEW
    {
        public int qnasId { get; set; }
        public Nullable<int> qnas_appId { get; set; }
        public string qnas_1 { get; set; }
        public string qnas_2 { get; set; }
        public string qnas_3 { get; set; }
        public string qnas_4 { get; set; }
        public string qnas_5 { get; set; }
        public string qnas_6 { get; set; }
        public string qnas_7 { get; set; }
        public string qnas_8 { get; set; }
        public string qnas_9 { get; set; }
        public string qnas_10 { get; set; }
        public string qnas_11 { get; set; }
        public string qnas_12 { get; set; }
        public string qnas_13 { get; set; }
        public string qnas_14 { get; set; }
        public string qnas_15 { get; set; }
        public string qnas_16 { get; set; }
        public string qnas_17 { get; set; }
        public string qnas_18 { get; set; }
        public string qnas_19 { get; set; }
        public string qnas_20 { get; set; }
        public string qnas_21 { get; set; }
        public Nullable<System.DateTime> qnas_date1 { get; set; }
        public string qnas_status { get; set; }
        public Nullable<int> qnas_madeby { get; set; }
        public Nullable<int> qnas_modifyby { get; set; }
        public Nullable<System.DateTime> qnas_date_created { get; set; }
        public Nullable<System.DateTime> qnas_date_modified { get; set; }
    }
}
