//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_QUERIES_AUTH
    {
        public int qaId { get; set; }
        public Nullable<int> qa_appId { get; set; }
        public Nullable<int> qa_from { get; set; }
        public Nullable<int> qa_to { get; set; }
        public Nullable<System.DateTime> qa_date { get; set; }
        public Nullable<int> qa_type { get; set; }
        public string qa_status { get; set; }
        public string qa_query { get; set; }
        public string qa_subject { get; set; }
        public Nullable<int> qa_branch { get; set; }
        public string qa_screen { get; set; }
        public Nullable<int> qa_close { get; set; }
        public Nullable<System.DateTime> qa_close_date { get; set; }
        public Nullable<int> qa_madeby { get; set; }
        public Nullable<System.DateTime> qa_date_created { get; set; }
        public Nullable<System.DateTime> qa_date_modified { get; set; }
        public string qa_coder_status { get; set; }
        public string qa_sub_status { get; set; }
    }
}
