//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_RADIOLOGY_REQUESTFORM
    {
        public int rdrf_Id { get; set; }
        public Nullable<int> rdrf_appId { get; set; }
        public string rdrf_radio { get; set; }
        public string rdrf_madeby { get; set; }
        public string rdrf_status { get; set; }
        public Nullable<System.DateTime> rdrf_date_created { get; set; }
        public Nullable<System.DateTime> rdrf_date_modified { get; set; }
        public string rdrf_finding { get; set; }
    }
}
