//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_RADIOLOGY_REPORTS
    {
        public int radrId { get; set; }
        public Nullable<int> radr_appId { get; set; }
        public Nullable<int> radr_ptId { get; set; }
        public string radr_title { get; set; }
        public string radr_report { get; set; }
        public string radr_type { get; set; }
        public string radr_status { get; set; }
        public Nullable<int> radr_madeby { get; set; }
        public Nullable<System.DateTime> radr_date_created { get; set; }
    }
}
