//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Referals
    {
        public int rId { get; set; }
        public Nullable<int> r_appId { get; set; }
        public Nullable<System.DateTime> r_date { get; set; }
        public string r_to { get; set; }
        public string r_mrno { get; set; }
        public string r_type { get; set; }
        public string r_reason { get; set; }
        public string r_history { get; set; }
        public string r_phy { get; set; }
        public string r_inv { get; set; }
        public string r_pro { get; set; }
        public string r_rec { get; set; }
        public string r_med { get; set; }
        public Nullable<System.DateTime> r_date_created { get; set; }
        public Nullable<System.DateTime> r_date_modified { get; set; }
        public Nullable<int> r_madeby { get; set; }
        public string r_status { get; set; }
    }
}
