//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Revision_Request_Form
    {
        public int rrfId { get; set; }
        public Nullable<int> rrf_appId { get; set; }
        public Nullable<System.DateTime> rrf_date1 { get; set; }
        public Nullable<System.DateTime> rrf_date2 { get; set; }
        public Nullable<System.DateTime> rrf_date3 { get; set; }
        public string rrf_1 { get; set; }
        public string rrf_2 { get; set; }
        public string rrf_3 { get; set; }
        public string rrf_4 { get; set; }
        public string rrf_5 { get; set; }
        public string rrf_6 { get; set; }
        public string rrf_7 { get; set; }
        public Nullable<int> rrf_made_by { get; set; }
        public string rrf_status { get; set; }
        public Nullable<int> rrf_modified_by { get; set; }
        public Nullable<System.DateTime> rrf_date_created { get; set; }
        public Nullable<System.DateTime> rrf_date_modified { get; set; }
    }
}
