//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_RESPONSES
    {
        public int resId { get; set; }
        public Nullable<int> res_query { get; set; }
        public string res_desc { get; set; }
        public string res_query_desc { get; set; }
        public Nullable<int> res_from { get; set; }
        public Nullable<int> res_to { get; set; }
        public Nullable<System.DateTime> res_date_created { get; set; }
        public Nullable<System.DateTime> res_date_modified { get; set; }
        public string res_read_status { get; set; }
        public string res_status { get; set; }
    }
}
