//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_RUNNING_PACKAGE
    {
        public int ccdtId { get; set; }
        public Nullable<int> ccdt_ptId { get; set; }
        public Nullable<int> ccdt_appId { get; set; }
        public Nullable<int> ccdt_InvId { get; set; }
        public Nullable<int> ccdt_patId { get; set; }
        public Nullable<System.DateTime> ccdt_exp_date { get; set; }
        public string ccdt_refNo { get; set; }
        public Nullable<int> ccdt_noSes { get; set; }
        public string ccdt_status { get; set; }
        public Nullable<System.DateTime> ccdt_date_created { get; set; }
        public Nullable<int> ccdt_madeby { get; set; }
    }
}
