//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_RUNNING_PACKAGE_SESSIONS
    {
        public int rpsId { get; set; }
        public Nullable<int> rps_ccdtId { get; set; }
        public Nullable<int> rps_appId { get; set; }
        public Nullable<int> rps_noses { get; set; }
        public string rps_status { get; set; }
        public Nullable<System.DateTime> rps_date_created { get; set; }
        public Nullable<int> rps_madeby { get; set; }
    }
}
