//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SICK_HAAD
    {
        public int shId { get; set; }
        public Nullable<int> sh_appId { get; set; }
        public string sh_ref { get; set; }
        public Nullable<System.DateTime> sh_date { get; set; }
        public string sh_time { get; set; }
        public Nullable<System.DateTime> sh_date1 { get; set; }
        public Nullable<System.DateTime> sh_date2 { get; set; }
        public string sh_remarks { get; set; }
        public string sh_status { get; set; }
        public Nullable<System.DateTime> sh_date_created { get; set; }
        public Nullable<System.DateTime> sh_date_modified { get; set; }
        public Nullable<int> sh_madeby { get; set; }
        public Nullable<int> sh_modifiedby { get; set; }
        public string sh_status2 { get; set; }
    }
}
