//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SIGNS
    {
        public int signId { get; set; }
        public int sign_appId { get; set; }
        public string sign_temp { get; set; }
        public string sign_pulse { get; set; }
        public string sign_bp { get; set; }
        public string sign_notes { get; set; }
        public string sign_height { get; set; }
        public string sign_weight { get; set; }
        public string sign_resp { get; set; }
        public string sign_spo2 { get; set; }
        public string sign_waist { get; set; }
        public string sign_hip { get; set; }
        public string sign_uri { get; set; }
        public string sign_head { get; set; }
        public Nullable<double> sign_bmi { get; set; }
        public string sign_status { get; set; }
        public Nullable<int> sign_madeby { get; set; }
        public Nullable<int> sign_modifyby { get; set; }
        public Nullable<System.DateTime> sign_date_created { get; set; }
        public Nullable<System.DateTime> sign_date_modified { get; set; }
        public string sign_bpd { get; set; }
    }
}
