//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SICK_LEAVE_MOH
    {
        public int slId { get; set; }
        public Nullable<int> sl_appId { get; set; }
        public string sl_words { get; set; }
        public Nullable<System.DateTime> sl_date1 { get; set; }
        public Nullable<System.DateTime> sl_date2 { get; set; }
        public Nullable<System.DateTime> sl_date_created { get; set; }
        public string sl_status { get; set; }
        public Nullable<int> sl_madeby { get; set; }
        public Nullable<int> sl_modifyby { get; set; }
        public Nullable<System.DateTime> sl_date_modified { get; set; }
    }
}
