//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SICK_LEAVE_MANUAL
    {
        public int slmId { get; set; }
        public Nullable<int> slm_appId { get; set; }
        public string slm_1 { get; set; }
        public Nullable<System.DateTime> slm_2 { get; set; }
        public Nullable<System.DateTime> slm_3 { get; set; }
        public string slm_4 { get; set; }
        public Nullable<System.DateTime> slm_date_created { get; set; }
        public Nullable<System.DateTime> slm_date_modified { get; set; }
        public string slm_status { get; set; }
        public Nullable<int> slm_madeby { get; set; }
        public Nullable<int> slm_modifiedby { get; set; }
    }
}
