//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SMSEmailWhatsapp_Tracking
    {
        public int SEWId { get; set; }
        public string SEW_Type { get; set; }
        public Nullable<System.DateTime> SEW_Timestamp { get; set; }
        public Nullable<int> SEW_ReceiverId { get; set; }
        public string SEW_ReceiverType { get; set; }
        public string SEW_ReceiverAccount { get; set; }
        public Nullable<int> SEW_ReferenceNo { get; set; }
        public string SEW_ReferenceType { get; set; }
        public Nullable<int> SEW_SendBy { get; set; }
        public Nullable<bool> SEW_Status { get; set; }
        public string SEW_Response { get; set; }
    }
}
