//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SPECIALTY
    {
        public int speId { get; set; }
        public string specialty { get; set; }
        public string spe_code { get; set; }
        public Nullable<int> specialty_dha { get; set; }
    }
}
