//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_START_END
    {
        public int tId { get; set; }
        public int t_appId { get; set; }
        public System.DateTime t_start { get; set; }
        public System.DateTime t_end { get; set; }
        public string t_duration { get; set; }
        public string t_status { get; set; }
    }
}
