//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Stress_Test_Form
    {
        public int stfId { get; set; }
        public Nullable<int> stf_appId { get; set; }
        public string stf_1 { get; set; }
        public string stf_status { get; set; }
        public Nullable<int> stf_made_by { get; set; }
        public Nullable<System.DateTime> stf_date_created { get; set; }
        public Nullable<int> stf_modified_by { get; set; }
        public Nullable<System.DateTime> stf_date_modified { get; set; }
    }
}
