//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TEETHS
    {
        public int thId { get; set; }
        public string th_uni { get; set; }
        public string th_int { get; set; }
        public string th_bri { get; set; }
    }
}
