//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TEMPLATE
    {
        public int TemplateId { get; set; }
        public string TempName { get; set; }
        public string TempContent { get; set; }
        public string TempFor { get; set; }
        public string TempStatus { get; set; }
        public Nullable<bool> TempWhatsapp { get; set; }
        public Nullable<bool> TempSMS { get; set; }
        public Nullable<bool> TempEmail { get; set; }
        public Nullable<int> TempCreatedBy { get; set; }
        public Nullable<System.DateTime> TempCreatedTimeStamp { get; set; }
        public Nullable<int> TempUpdatedBy { get; set; }
        public Nullable<System.DateTime> TempUpdatedTimeStamp { get; set; }
    }
}
