//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Template_Parameters
    {
        public int TParamId { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string TParamKey { get; set; }
        public string TParamType { get; set; }
        public string TParamValue { get; set; }
        public Nullable<bool> TParamStatus { get; set; }
        public Nullable<int> TParamCreatedBy { get; set; }
        public Nullable<System.DateTime> TParamCreatedTimeStamp { get; set; }
        public Nullable<int> TParamUpdatedBy { get; set; }
        public Nullable<System.DateTime> TParamUpdatedTimeStamp { get; set; }
    }
}
