//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TREATMENTS
    {
        public int trId { get; set; }
        public Nullable<int> tr_dept { get; set; }
        public Nullable<int> tr_ins { get; set; }
        public string tr_code { get; set; }
        public string tr_name { get; set; }
        public Nullable<decimal> tr_price { get; set; }
        public string tr_type { get; set; }
        public Nullable<double> tr_disc { get; set; }
        public string tr_icode { get; set; }
        public string tr_category { get; set; }
        public string tr_lab_dept { get; set; }
        public string tr_lcode { get; set; }
        public Nullable<int> tr_group { get; set; }
        public Nullable<int> tr_branch { get; set; }
        public string tr_class { get; set; }
        public Nullable<int> tr_parent { get; set; }
        public Nullable<decimal> tr_cost { get; set; }
        public Nullable<int> tr_itype { get; set; }
        public string tr_tooth { get; set; }
        public string tr_disc_type { get; set; }
        public Nullable<System.DateTime> tr_start_date { get; set; }
        public Nullable<System.DateTime> tr_end_date { get; set; }
        public Nullable<double> tr_vat { get; set; }
        public Nullable<decimal> tr_disc_value { get; set; }
        public Nullable<double> tr_vat2 { get; set; }
        public string tr_dent_option { get; set; }
        public string tr_dent_option_1 { get; set; }
        public string tr_dent_option_2 { get; set; }
        public string tr_tat { get; set; }
        public string tr_norm_range { get; set; }
        public string tr_methodology { get; set; }
        public string tr_units { get; set; }
        public Nullable<double> tr_tat2 { get; set; }
        public string tr_footer { get; set; }
        public string tr_format { get; set; }
        public Nullable<int> tr_rdays { get; set; }
        public Nullable<int> tr_madeby { get; set; }
        public Nullable<int> tr_modifyby { get; set; }
        public Nullable<System.DateTime> tr_date_created { get; set; }
        public Nullable<System.DateTime> tr_date_modified { get; set; }
        public string tr_status { get; set; }
    }
}
