//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Treatment_Images
    {
        public int tiId { get; set; }
        public Nullable<int> ti_ptId { get; set; }
        public Nullable<int> ti_appId { get; set; }
        public string ti_image { get; set; }
        public string ti_image_2 { get; set; }
        public string ti_image_3 { get; set; }
        public string ti_image_4 { get; set; }
        public string ti_image_5 { get; set; }
        public string ti_image_6 { get; set; }
        public string ti_image_7 { get; set; }
        public string ti_image_8 { get; set; }
        public string ti_image_9 { get; set; }
        public string ti_image_10 { get; set; }
        public string ti_lab_1 { get; set; }
        public string ti_lab_2 { get; set; }
        public string ti_lab_3 { get; set; }
        public string ti_lab_4 { get; set; }
        public string ti_lab_5 { get; set; }
        public string ti_lab_6 { get; set; }
        public string ti_lab_7 { get; set; }
        public string ti_lab_8 { get; set; }
        public string ti_lab_9 { get; set; }
        public string ti_lab_10 { get; set; }
        public string ti_lab_11 { get; set; }
        public string ti_lab_12 { get; set; }
        public string ti_lab_13 { get; set; }
        public string ti_lab_14 { get; set; }
        public string ti_lab_15 { get; set; }
        public string ti_lab_16 { get; set; }
        public string ti_lab_17 { get; set; }
        public string ti_loinc_1 { get; set; }
        public string ti_loinc_2 { get; set; }
        public string ti_loinc_3 { get; set; }
        public string ti_loinc_4 { get; set; }
        public string ti_loinc_5 { get; set; }
        public string ti_loinc_6 { get; set; }
        public string ti_loinc_7 { get; set; }
        public string ti_loinc_8 { get; set; }
        public string ti_loinc_9 { get; set; }
        public string ti_loinc_10 { get; set; }
        public string ti_loinc_11 { get; set; }
        public string ti_loinc_12 { get; set; }
        public string ti_loinc_13 { get; set; }
        public string ti_loinc_14 { get; set; }
        public string ti_loinc_15 { get; set; }
        public string ti_bimage_1 { get; set; }
        public string ti_bimage_2 { get; set; }
        public string ti_bimage_3 { get; set; }
        public string ti_bimage_4 { get; set; }
        public string ti_bimage_5 { get; set; }
        public string ti_bimage_1_icon { get; set; }
        public string ti_bimage_2_icon { get; set; }
        public string ti_bimage_3_icon { get; set; }
        public string ti_bimage_4_icon { get; set; }
        public string ti_bimage_5_icon { get; set; }
        public string ti_image_1_type { get; set; }
        public string ti_image_2_type { get; set; }
        public string ti_image_3_type { get; set; }
        public string ti_image_4_type { get; set; }
        public string ti_image_5_type { get; set; }
        public string ti_status { get; set; }
        public Nullable<System.DateTime> ti_date_created { get; set; }
        public Nullable<System.DateTime> ti_date_modified { get; set; }
        public Nullable<int> ti_madeby { get; set; }
        public Nullable<int> ti_modifyby { get; set; }
    }
}
