//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_VACCINATIONS
    {
        public int vId { get; set; }
        public string v_code { get; set; }
        public string v_name { get; set; }
        public string v_status { get; set; }
        public Nullable<int> v_madeby { get; set; }
        public Nullable<System.DateTime> v_date_created { get; set; }
        public Nullable<System.DateTime> v_date_modified { get; set; }
    }
}
